pentaho/pentaho-hadoop-shims

hive-jdbc/src/org/apache/hadoop/hive/jdbc/HiveDriver.java, hive-jdbc/src/org/apache/hive/jdbc/HiveDriver.java, hive-jdbc/src/org/apache/hive/jdbc/ImpalaDriver.java, hive-jdbc/test-src/org/apache/hadoop/hive/jdbc/HiveDriverTest.java, hive-jdbc/test-src/org/apache/hive/jdbc/HiveDriverTest.java, hive-jdbc/test-src/org/apache/hive/jdbc/ImpalaDriverTest.java
From previous fixes/cases, we missed the case where the driver is not present but we call connect() on it anyway. The current behavior throws an exception that connect does not catch.  I believe getActiveDriver() should not throw an exception if the driver cannot be found; rather it should return null, and everyone that needs the active driver (callWithActiveDriver, connect, e.g.) should deal with both null and exception conditions as appropriate.
=> [PDI-13407]: Fixed error in Hive/Impala drivers during connect / getActiveDriver()

hdp22/ivy.xml
Temporarily excluded 
* pentaho-aggdesigner-algorithm-5.1.3-jhyde.jar,
* jetty-6.1.26.hwx.jar
* jetty-util-6.1.26.hwx.jar
files to workaround build failure.
=> [BAD-140] - [BAD-140] - Compile HDP 2.2 shim

mapr31/package-res/config.properties
@mattyb149, could you review please
I've make changes according to your proposals ( http://jira.pentaho.com/browse/PDI-12886 ).
Supposed that path to sqoop libs user will fill by himself. It's beacause we have no possibility to detect where sqoop has been installed.
=> [PDI-12886] - PDI Sqoop Jobs fail when SQOOP_HOME is defined

common/test-src/org/pentaho/hadoop/shim/common/CommonPigShimTest.java, hdp21/ivy.xml, hdp22/ivy.xml
Changes:
* added mockito dependency for hdp21 and hdp22
* simplified TestPigShim.executeScript() method to avoid hdp22 compilation error because of changes in GruntParser API (the method is only used to have concrete class and is never invoked).
=> [TEST]-fix hdp related unit tests

mapr401/build.properties
=> [BAD-165] - MapR401: All Sqoop jobs fail if MapR cluster is running Hadoop 2.4 version

mapr401/build.properties, mapr401/ivy.xml, mapr401/package-res/config.properties
=> [PDI-13635]- MapR: Yarn job fails on MapR Hadoop 4.0.1 on Windows client

cdh53/package-res/mapred-site.xml
Adds mapreduce.app-submission.cross-platform setting to mapred-site.xml, in order to allow Windows users to submit jobs to a Hadoop cluster
=> BAD-148: Add Cross-Platform MR Submission Setting

emr34/ivy.xml
=> [BACKLOG-3217] - EMR34 shim requires additional changes to run MapReduce jobs with Input-Output folders on S3

mapr401/src/org/pentaho/hbase/shim/mapr401/MapRHBaseConnection.java
Overridden classes for new version hbase
=> [BACKLOG-3253] - HBase Input fails if Filter condition is specified

mapr410/ivy.xml
Modified to use h2 classifier for pig jar.
=> [BAD-293] - MapR410: Pig job fails due to wrong jar in the shim

emr34/build.properties, emr34/ivy.xml, emr34/src/org/pentaho/hadoop/shim/emr34/SnappyShim.java, hdp20/build.properties, hdp20/ivy.xml, hdp21/build.properties, hdp21/ivy.xml, hdp22/build.properties, hdp22/ivy.xml, mapr401/build.properties, mapr401/ivy.xml, mapr401/src/org/pentaho/hadoop/shim/mapr401/SnappyShim.java
* Removed necessary for old shims pentaho-snappy artifact.
=> [BAD-318] Hadoop File Output/Input steps fail to output to HDFS with Hadoop-snappy compression

emr34/ivy.xml
* Added missed pentaho-vfs jar to dist
* Removed unnecessary for runtime shims-api jar
=> [BACKLOG-5188] -  [REGRESSION]: EMR34 shim: Unable to load shim error.

hdp22/build.properties, hdp22/ivy.xml
Reverts pentaho/pentaho-hadoop-shims#285
=> Revert "[BACKLOG-5265] - Excluding jersey jars from client config"

emr41/ivy.xml
=> [BAD-436] - Exclude xml-apis-1.3.04.jar from emr 4.1 shim

cdh55/ivy.xml
Although the BAD-446 is closed - the decision has been made to use jackson 2.2.3 everywhere instead of 2.2.2 in some places (hive deps)
see also related COMP cases:
http://jira.pentaho.com/browse/COMP-2470
http://jira.pentaho.com/browse/COMP-2471
http://jira.pentaho.com/browse/COMP-2472 - has cite with the decision documented
@brosander @hudak Gentlemen, I'll appreciate if you had a chance to take a look
=> [BAD-446] - Create and compile CDH 5.5 shim in the 6.0 branch

common/src/org/pentaho/hbase/shim/common/CommonHBaseConnection.java
Add Configuration argument to getHBaseClientFactory() method.
=> [PDI-14443] - Hadoop Kerberos security ticket not renewed after expire

common/src/org/pentaho/hadoop/shim/common/DistributedCacheUtilImpl.java, common/test-src/org/pentaho/hadoop/shim/common/DistributedCacheUtilImplTest.java
* Added test for mixed entries in zip
=> [BACKLOG-5746] - Spoon: PMR jobs failed because pentaho-mapreduce-libraries.zip can't be unzipped successfully

cdh55/build.properties, cdh55/ivy.xml
we're supposed to rely on kettle-engine for the commons-collections component
leave it only for test and provided configurations so that it won't get into assembly
@brosander @hudak
=> [BAD-456] - get rid of commons-collections in the shim

hdp22/ivy.xml
=> [BACKLOG-6571] - Mock and Unit Test Jars in Shim distribition

hdp22/ivy.xml
Done the same way as in other shims.
@brosander @hudak
=> [BACKLOG-6294] - Commons-collections jars should be removed from HDP2.2 shim

cdh54/src/org/apache/hadoop/hive/jdbc/HiveDriver.java, cdh55/src/org/apache/hadoop/hive/jdbc/HiveDriver.java, common/test-src/org/pentaho/hadoop/shim/common/DriverProxyInvocationChainTest.java, hdp23/src/org/apache/hadoop/hive/jdbc/HiveDriver.java, hive-jdbc/src/org/apache/hadoop/hive/jdbc/HiveDriver.java, hive-jdbc/test-src/org/apache/hadoop/hive/jdbc/HiveDriverTest.java
There are two issues here:
1. JDBC connection is not stored properly in BI Server repository
2. Incorrect error message displayed upon connection failure
The changes in this commit fix only the second issue.
It is caused by the fact that connect() method of Pentaho Hive1 driver threw exception when called by DriverManager with impala-url.
This happens since Hive1 JDBC driver in latest shims throws exception in constructor.
The fix is to return null instead if the caught exception has special flag indicating that this is not a real driver but a mocking stub.
The flag is propagated through SQLState property of SQLException class.
@brosander @hudak
=> [BACKLOG-6547] - CDH55 secure shim: PUC: DB Table(s) Data Source cannot be created based on Secured Cloudera Impala JDBC connection

common/src-hadoop-shim-1.0/org/pentaho/hadoop/shim/common/ConfigurationProxyV2.java, hsp101/src/org/pentaho/hadoop/shim/hsp101/authorization/ShimNoOpHadoopAuthorizationService.java, mapr401/src/org/pentaho/hadoop/shim/mapr401/ConfigurationProxyV2.java, mapr410/src/org/pentaho/hadoop/shim/mapr410/ConfigurationProxyV2.java
* Mistype in package name
* Change the way of getting job conf in constructor which caused fail on init
=> [BAD-494] - MapR 4.1: Pig, Sqoop impersonated users are not picked up in 6.1 release

hdp24/ivy.xml
There was duplication of jars for hdp24 in hdp24/lib, hdp24/lib/client, hdp24/lib/pmr.
Fixed with excluding hadoop-hdfs module from default config.
=> [BAD-507]: PMR job can't be finish successfully because of time out exception on hdp 2.4 secure cluster

hdp24/ivy.xml
Antlr dependency has been excluding fromshims distribution since the first shim. Hive and Pig have different antlr dependencies. So to not produce conflict this library was exluded - to force user choose manually which version of the antlr library suits him. Checking HDP24 shim was found that Hive->Antlr 3.4 and PIG->Antlr 3.4,3.3. 
It was decided to use antlr 3.4 version  coming from hive.
New introduced dependencies: 
-antlr-runtime-3.4.jar
-antlr-2.7.7.jar
-stringtemplate-3.2.1.jar
=> [BACKLOG-6693] - Pig job failed on the DI server with NoSuchMethod error.

cdh57/build.properties, cdh57/ivy.xml
metrics-core-2.2.0.jar is needed for hbase-client and should be included into PMR configuration otherwise we have java.lang.NoClassDefFoundError: com/yammer/metrics/core/Gauge
at working with Hbase steps
This jar has already been uploaded into pentaho private-3rd-party-candidate-release repo and processed (please see http://jira.pentaho.com/browse/COMP-957)
=> [BAD-509]: Create and Compile CDH 5.7 SHIM against Pentaho 6.1.x

emr46/ivy.xml
It needs to delete hbase-examples-1.2.0 from EMR 4.6 shim because it has been rejected on Architecture Review (see COMP-3144).
=> [BACKLOG-9277]: Delete hbase-examples-1.2.0 from EMR 4.6 shim

cdh55/package-res/config.properties
=> [BACKLOG-9012][TYPO] - Master: cdh55 shim in CE-version: configuration name should be updated in the "config.properties" file

emr46/build.properties, emr46/ivy.xml
Fix the global version property for pentaho-hadoop-shims-api-test
=> [BACKLOG-8533]: Create the EMR 4.6 Shim (against Pentaho Master/7.0)

emr46/build.properties, emr46/ivy.xml
Fix the global version property for pentaho-hadoop-shims-api-test
=> [BACKLOG-8532]: Create the EMR 4.6 Shim (against Pentaho 6.1)

api/src/org/pentaho/hadoop/shim/HadoopConfigurationLocator.java, api/test-src/org/pentaho/hadoop/shim/HadoopConfigurationLocatorTest.java
- added a new property exclude.jars to the config.properties file for a shim. This property contains the list of the excluded jars (without version, for instance, xercesImpl,xmp-apis) from the classpath;
- created a new method filterJars in pentaho-hadoop-shims/api/src/org/pentaho/hadoop/shim/HadoopConfigurationLocator;
- added changes to createConfigurationLoader (added calling the filterJars method );
- created new Tests in pentaho-hadoop-shims/api/test-src/org/pentaho/hadoop/shim/HadoopConfigurationLocatorTest.
=> [BACKLOG-9528] - YARN job fails on MapR 5.1 unsecure cluster while runing a transformation step

common/src-modern/org/pentaho/hadoop/shim/common/authorization/AuthenticatingHadoopShim.java, common/test-src-modern/org/pentaho/hadoop/shim/common/authorization/AuthenticatingHadoopShimTest.java
We want the failover to work all the time for now as well, except when the impersonation type=disabled, which means no Kerberos at all.
=> [BACKLOG-9591]-As a BDS administrator, I want one place to configure big data security to ease configuration tasks.

common/src/org/pentaho/hadoop/shim/common/CommonHadoopShim.java
* As Impala type uses "org.apache.hive.jdbc.HiveDriver"  - this driver was registered in DriverManager together with wrapped in DriverProxyInvocationChain HiveDriver.
=> [BACKLOG-9547]-[DEV] - Update the impersonation code to add impersonating impala driver to the map of loaded drivers

api/src/org/pentaho/hadoop/shim/HadoopConfigurationLocator.java, api/test-src/org/pentaho/hadoop/shim/HadoopConfigurationLocatorTest.java, api/test-src/org/pentaho/hadoop/shim/HadoopExcludeJarsTest.java
Repaired two of my tests because they failed on Linux: 
http://devci.pentaho.com/job/master-snapshot/job/big-data-hadoop-shims/679/ .
Created new class HadoopExcludeJarsTest, added more tests to check changed regular expression.
=> [BACKLOG-9528] -  YARN job fails on MapR 5.1 unsecure cluster while runing a transformation step (tests passed on Windows but failed on Linux)

mapr510/build.properties
Added oss-license.filename=PentahoHadoopShim_mapr510_OSS_Licenses.html in the build.property file.
=> [BACKLOG-8539] - Create the MapR 5.1 Shim (against Pentaho 6.1)  - add oss-license.filename property

mapr510/build.properties
Added oss-license.filename=PentahoHadoopShim_mapr510_OSS_Licenses.html in the build.property file.
=> [BACKLOG-8540] - Create the MapR 5.1 Shim (against Pentaho 7.0) - add oss-license.filename property

api/src/org/pentaho/hadoop/shim/HadoopConfigurationLocator.java, api/test-src/org/pentaho/hadoop/shim/HadoopExcludeJarsTest.java
Added changes  (that should be included in the PATCH) to the 6.1 branch in MapR 5.1 shim.
The changes are the same as for the master branch (https://github.com/pentaho/pentaho-hadoop-shims/pull/378, https://github.com/pentaho/pentaho-hadoop-shims/pull/381):
- created a new method filterJars in pentaho-hadoop-shims/api/src/org/pentaho/hadoop/shim/HadoopConfigurationLocator;
- added changes to the createConfigurationLoader method (added calling the filterJars method );
- created a new class HadoopExcludeJarsTest.
=> [BACKLOG-10554] - YARN, PMR Hadoop jobs fail on the 6.1 branch on MapR 5.1 unsecure cluster while runing a transformation step

api/src/main/java/org/pentaho/hadoop/shim/HadoopConfigurationLocator.java, api/src/test/java/org/pentaho/hadoop/shim/HadoopExcludeJarsTest.java, api/src/test/resources/pmr.properties, shims/mapr520/assemblies/mapr520-shim/src/assembly/assembly.xml, shims/mapr520/assemblies/mapr520-shim/src/main/resources/config.properties
To get all HBase-related steps working, including HBase Row decoder Step, I excluded hadoop-common-2.7.0-mapr-1602.jar from HadoopConfigurationClassLoader on the cluster side only and moved hbase-related jars (for HBase Row Decoder Step) from mapr520/lib folder to mapr520/lib/pmr folder.
Updated pentaho-hadoop-shims-api module:
- added exclude.cluster.jars property to hadoop-shims-api module (HadoopConfigurationLocator class).
Updated pentaho-hadoop-shims-mapr520 module:
- moved hbase artifacts (shims/mapr520 module) from mapr520/lib folder to mapr520/lib/pmr folder;
- updated config.properties file for mapr520 shim (added exclude.cluster.jars property).
See this PR with https://github.com/pentaho/pentaho-big-data-ee/pull/174
=> [BAD-592]-MapR 5.1/5.2: ClassNotFoundException when running MapReduce Job with mapper containing Hbase Row Decoder step

shims/mapr520/assemblies/mapr520-shim/src/main/resources/config.properties
Replaced "ignore.classes=" with "ignored.classes=" as was earlier in config.properties
=> [BACKLOG-15584]-MapR5.2: Hadoop Cluster Test fails (JAAS configuration could not be loaded at this time)

api/src/main/java/org/pentaho/hadoop/shim/HadoopConfigurationLocator.java, api/src/test/java/org/pentaho/hadoop/shim/HadoopExcludeJarsTest.java, api/src/test/resources/pmr.properties, shims/mapr520/assemblies/mapr520-shim/src/assembly/assembly.xml, shims/mapr520/assemblies/mapr520-shim/src/main/resources/config.properties
Reverts pentaho/pentaho-hadoop-shims#452
=> Revert "[BAD-592]-MapR 5.1/5.2: ClassNotFoundException when running MapReduce Job with mapper containing Hbase Row Decoder step"

shims/hdp24/assemblies/hdp24-shim/src/main/resources/core-site.xml, shims/hdp25/assemblies/hdp25-shim/src/main/resources/core-site.xml
Added core-site.xml to both hdp24 and hdp25 shims into pentaho-hadoop-shims\shims\hdp24\assemblies\hdp24-shim\src\main\resources and pentaho-hadoop-shims\shims\hdp25\assemblies\hdp25-shim\src\main\resources appropriately.
=> [BACKLOG-15983]-HDP shims don't contain core-site.xml

api/src/main/java/org/pentaho/hadoop/shim/HadoopConfigurationLocator.java, api/src/test/java/org/pentaho/hadoop/shim/HadoopRunningOnClusterTest.java, api/src/test/resources/pmr.properties, shims/mapr520/assemblies/mapr520-shim/src/assembly/assembly.xml, shims/mapr520/impl/pom.xml
To get all HBase-related steps working, including HBase Row decoder Step:
- added isRunningOnCluster method to the HadoopConfigurationLocator class to avoid using linux.class.path  (from config.properties file) on the cluster side;
- moved hbase-related jars (for HBase Row Decoder Step) from mapr520/lib folder to mapr520/lib/pmr folder.
To get PMR-related steps working after previous changes I added new flexjson jar to mapr520/lib/pmr folder.
See this PR with https://github.com/pentaho/pentaho-big-data-ee/pull/177
=> [BACKLOG-15823]-MapR 5.1/5.2: ClassNotFoundException when running MapReduce Job with mapper containing Hbase Row Decoder step

pom.xml, shims/pom.xml
Added exclusion of commons-io jar to pentaho-hadoop-shims-common-shim artifact (shims/pom.xml) to get the correct version of commons-io-2.4.jar inside hdp26 zip archive (client folder).
=> [BAD-647]-Create and Dev Validate the HDP 2.6 shim against Pentaho Master / 8.0

shims/cdh510/assemblies/cdh510-shim/src/main/resources/config.properties, shims/cdh59/assemblies/cdh59-shim/src/main/resources/config.properties
Removed security properties from config.ptoperties files for both cdh59 and cdh510 CE shims.
=> [BAD-663]-Security reveal of settings in config.properties for cdh shims in 7.0, 7.1

shims/hdp25/assemblies/hdp25-shim/pom.xml, shims/hdp25/assemblies/hdp25-shim/src/assembly/assembly.xml, shims/hdp25/impl/pom.xml, shims/hdp26/assemblies/default/src/assembly/assembly.xml, shims/hdp26/assemblies/hdp26-shim/pom.xml, shims/hdp26/assemblies/hdp26-shim/src/assembly/assembly.xml, shims/hdp26/default/pom.xml, shims/hdp26/pom.xml
After this pull request https://github.com/pentaho/pentaho-hadoop-shims/pull/485/files some new additional unwanted components appeared in hdp25 and hdp26 Shims:
- zookeeper-3.4.6.2.6.0.3-8.jar in assembly archive hdp26/lib folder;
- apacheds-i18n-2.0.0-M5.jar instead of apacheds-i18n-2.0.0-M15.jar in assembly archive hdp25/lib/client;
- json-smart-1.2.jar instead of json-smart-1.1.1.jar  in assembly archive hdp25/lib/client.
I updated the pull request to avoid adding these unwanted artifacts to assembly archive.
=> [COMP-5866]-update json-smart artifact version property

shims/pom.xml
@lgrill-pentaho @VasilinaTerehova @abaskakau 
this will let us release shims individually with e.g. mvn -DskipDefault -P hdi35 deploy
this is the same strategy used in platform and kettle
=> [ENGOPS-3274] put shim modules in profiles

api/src/main/java/org/pentaho/hadoop/shim/api/DistributedCacheUtil.java, common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/DistributedCacheUtilImpl.java, common/mapred/src/main/java/org/pentaho/hadoop/mapreduce/MRUtil.java
want all my transformations and jobs to use the defined cluster name as
the reference to the cluster so   I only need to update any of the cluster
information from one place. (hdfs)
=> [BACKLOG-17014]-As an ETL developer after defining a “Named Cluster”, I

pom.xml
Added httpclient exclusion to kettle-engine
=> [BACKLOG-19339]-CDH shims contain incorrect httpclient version

common/common-shim/src/test/java/org/pentaho/hadoop/shim/common/format/orc/PentahoOrcReadWriteTest.java
Fixes a compilation error in the hadoop common shim hidden by a preprocess error.
=> [BACKLOG-20291] Add overwrite existing flag in Orc Output step

common-services-api/jdbc/pom.xml
@smaring @rmansoor Please review.
=> [CLEANUP] Fix compilation error due to incorrect pentaho-metastore-locator-api version.

shims/cdh513/assemblies/client/src/assembly/assembly.xml
Excluded hadoop-client as it doesn`t contain any java classes and it needs only for building cdh513 module.
Added hadoop-related jars as they are getting transitively by hadoop-client
=> [BAD-1107]-exclude hadoop-client from cdh513 archive

shims/cdh514/impl/src/main/resources/META-INF/services/org.pentaho.hadoop.shim.common.authorization.NoOpHadoopAuthorizationService
Updated NoOpHadoopAuthorizationService
=> [BACKLOG-22296]-CDH514 EE shim can not be loaded in Pentaho

api/pom.xml
**Warning:** To be merged together with all other projects that need this change, **please do not merge** until then 
**This PR relates to:**
https://github.com/pentaho/pentaho-commons-database/pull/152
https://github.com/pentaho/apache-vfs-browser/pull/42
https://github.com/pentaho/data-access/pull/992
https://github.com/pentaho/mondrian/pull/1033
https://github.com/pentaho/pdi-jms-plugin/pull/53
https://github.com/pentaho/pdi-platform-utils-plugin/pull/92
https://github.com/pentaho/pdi-sap-hana-bulk-loader-plugin/pull/76
https://github.com/pentaho/pdi-teradata-tpt-plugin/pull/39
https://github.com/pentaho/big-data-plugin/pull/1340
https://github.com/pentaho/pentaho-cassandra-plugin/pull/106
https://github.com/pentaho/pentaho-data-mining/pull/15 …
=> [BACKLOG-19695] Update commons-vfs2 artifact version from 2.1 to 2.2

shims/cdh514/client/src/assembly/assembly.xml
Removed vulnerable component according to https://jira.pentaho.com/browse/BACKLOG-21295
=> [BAD-1451]-Remove of vulnerable component hadoop-yarn-server-nodemanager from cdh514 shim

shims/hdp26/hive/pom.xml, shims/hdp26/pom.xml, shims/pom.xml
hive-metastore was defined twice as a dependency.
Removed the redundant dependency and replaced it with the missing hive-storage-api dependency.
=> [BACKLOG-24170] - Added missing ORC format dependencies for hdp26.

.gitignore, common-services-api/api/src/main/java/org/pentaho/hadoop/shim/spi/FormatShim.java, common-services-api/format/pom.xml, common-services-api/format/src/main/java/org/pentaho/bigdata/api/format/FormatService.java, common-services/format/src/main/java/org/pentaho/big/data/impl/shim/format/FormatServiceImpl.java, common/common-format/src/it/java/org/pentaho/hadoop/shim/common/CommonFormatShimTestIT.java, common/common-format/src/main/java/org/pentaho/hadoop/shim/common/CommonFormatShim.java, common/common-format/src/main/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroInputFormat.java, common/common-format/src/main/java/org/pentaho/hadoop/shim/common/format/orc/PentahoOrcInputFormat.java, common/common-format/src/main/java/org/pentaho/hadoop/shim/common/format/parquet/PentahoParquetInputFormat.java, common/common-format/src/test/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroInputFormatTest.java, common/common-format/src/test/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroReadWriteTest.java, common/common-format/src/test/java/org/pentaho/hadoop/shim/common/format/avro/StreamingInputTest.java, common/common-format/src/test/java/org/pentaho/hadoop/shim/common/format/orc/PentahoOrcInputFormatTest.java, common/common-format/src/test/java/org/pentaho/hadoop/shim/common/format/orc/PentahoOrcReadWriteTest.java, common/common-format/src/test/java/org/pentaho/hadoop/shim/common/format/parquet/PentahoParquetInputFormatTest.java, common/common-format/src/test/java/org/pentaho/hadoop/shim/common/format/parquet/PentahoParquetRecordWriterTest.java, common/modern/src/main/java/org/pentaho/hadoop/shim/common/delegating/DelegatingFormatShim.java, pom.xml
https://github.com/pentaho/big-data-plugin/pull/1455
=> [BACKLOG-24118] - Parquet Input fails on Secured shims moved to OSGI (EE specific)

shims/hdp30/client/pom.xml
=> [BACKLOG-25619] - HDP30 shim: Hive2 connection cannot be established using hdp30 shim

shims/hdp30/default/src/assembly/assembly.xml
=> [BACKLOG-25703] - HDP 3.0 - Added missing dependency for com/codahale/metrics/Metric

common/common-shim/pom.xml, pom.xml, shims/cdh512/impl/pom.xml, shims/cdh513/impl/pom.xml, shims/cdh514/impl/pom.xml, shims/cdh601/impl/pom.xml, shims/emr511/client/pom.xml, shims/emr511/client/src/assembly/assembly.xml, shims/emr511/impl/pom.xml, shims/emr511/pom.xml, shims/emr59/client/pom.xml, shims/emr59/impl/pom.xml, shims/emr59/pom.xml, shims/hdi35/client/pom.xml, shims/hdi35/default/pom.xml, shims/hdi35/impl/pom.xml, shims/hdi35/pom.xml, shims/hdp25/impl/pom.xml, shims/hdp26/impl/pom.xml, shims/hdp30/impl/pom.xml, shims/mapr520/impl/pom.xml, shims/mapr60/impl/pom.xml
Starting with version 1.9, the `aws-java-sdk` was split into multiple JAR files. Because we were importing both `aws-java-sdk` and `aws-java-sdk-core`, multiple implementations of the same class were found.
This was fixed, as well as a major cleanup of the dependencies for `aws-java-sdk-*` and also for jackson dependencies that were still referencing old versions and are now managed in the parent POM.
Moved dependency management of `aws-java-sdk-*` into the root pom of this project.
@pentaho/tatooine please review and merge.
=> [BAD-1549] EMR 5.11 shim contains conflicting JARs

pom.xml, shims/cdh601/client/pom.xml, shims/hdp25/assemblies/hdp25-shim/src/assembly/assembly.xml, shims/hdp25/impl/pom.xml
@graimundo and @Pancho7 please review.
Replaces https://github.com/pentaho/pentaho-hadoop-shims/pull/931.
=> [BACKLOG-27566] Remove SLF4J libs from shims

pom.xml
This is a series of PRs to update the version of AWS Java SDK across all repositories.
See: pentaho/maven-parent-poms#114
@pentaho/tatooine @ricardosilva88 @ssamora
=> [PDI-17867] Fixes not closing connections leading to timeouts

common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/AvroNestedReader.java, common/common-shim/src/test/java/org/pentaho/hadoop/shim/common/format/avro/StreamingInputTest.java
avoid overwriting incoming data.
This commit is a cherry-pick from 9.0.0.0 master commit 5cea343.
=> [SP-5143] Ensure a new array gets allocated for output data to

common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/CommonHadoopShim.java
to ensure it finds the correct .properties file.
=> [BACKLOG-30615] Set classloader when accessing Hadoop VersionInfo class

common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/ShimConfigsLoader.java
Fixed InputStream not getting closed and leaving the config.properties locked and unable to be deleted during NamedCluster editing.
=> [BACKLOG-31555] Fixed InputStream not getting closed and leaving the config.properties locked and unable to be deleted during NamedCluster editing.

common-services-api/src/main/java/org/pentaho/big/data/api/cluster/service/locator/impl/NamedClusterServiceLocatorImpl.java, common-services-api/src/test/java/org/pentaho/big/data/api/cluster/service/locator/impl/NamedClusterServiceLocatorImplTest.java
Allowing a shim service to be retrieved even if no named cluster
is applicable.  Needed for S3, HCP, etc.
https://jira.pentaho.com/browse/BACKLOG-30640
=> [BACKLOG-30640] Avro Output - Generate file without shim specified

shims/apache/driver/pom.xml, shims/apache/driver/src/main/java/org/pentaho/hadoop/shim/HadoopShim.java, shims/apache/driver/src/main/resources/OSGI-INF/blueprint/blueprint.xml, shims/apache/kar/pom.xml, shims/apache/kar/src/main/feature/feature.xml, shims/apache/pom.xml, shims/pom.xml
Will serve as an internal fallback shim to be used in cases
where a vendor shim is not applicable, e.g. Avro->HCP
=> [BACKLOG-30640] Generic Apache Shim

common-services-api/src/main/java/org/pentaho/big/data/api/cluster/service/locator/impl/NamedClusterServiceLocatorImpl.java, common-services-api/src/main/resources/OSGI-INF/blueprint/blueprint.xml, common-services-api/src/test/java/org/pentaho/big/data/api/cluster/service/locator/impl/NamedClusterServiceLocatorImplTest.java, shim-api/src/main/java/org/pentaho/hadoop/shim/api/cluster/NamedClusterServiceLocator.java
Configuration managed by osgi, rather than metastore.  Can be overriden
by setting the internal.shim property in `karaf/etc/pentaho.shim.cfg`
https://jira.pentaho.com/browse/BACKLOG-30640
=> [BACKLOG-30640] Removing the "DefaultShim" in favor of internal shim

common-services-api/src/main/java/org/pentaho/big/data/api/cluster/service/locator/impl/NamedClusterServiceLocatorImpl.java, common-services-api/src/test/java/org/pentaho/big/data/api/cluster/service/locator/impl/NamedClusterServiceLocatorImplTest.java
- removes dependence on guava Multimap
- simplifies logic by removing rank ordering, which has never been used.
=> [BACKLOG-30640] Refactoring NamedCLusterServiceLocatorImpl

shims/apache/driver/src/main/java/org/pentaho/hadoop/shim/pvfs/PvfsHadoopBridge.java, shims/apache/driver/src/main/java/org/pentaho/hadoop/shim/pvfs/conf/HCPConf.java, shims/apache/driver/src/main/java/org/pentaho/hadoop/shim/pvfs/conf/PvfsConf.java, shims/apache/driver/src/main/java/org/pentaho/hadoop/shim/pvfs/conf/S3Conf.java, shims/apache/driver/src/test/java/org/pentaho/hadoop/shim/pvfs/PvfsHadoopBridgeTest.java, shims/apache/driver/src/test/java/org/pentaho/hadoop/shim/pvfs/conf/HCPConfTest.java, shims/apache/driver/src/test/java/org/pentaho/hadoop/shim/pvfs/conf/S3ConfTest.java
Disabling FileSystem caching in the static FileSystem cache,
handling in the PvfsHadoopBridge.  This avoids reusing cached
filesystems that were created with different credentials in effect.
As part of this change, updated the bridge getFileStatus and listStatus
to return FileStatus with the pvfs paths set, rather than the path
of the underlying fs.  Formerly we were able to return the underlying
fs path, since those paths would be resolved against the cached fs.
Now we need to make sure actions on those paths still comes through
the pvfs bridge.
https://jira.pentaho.com/browse/BACKLOG-30638
https://jira.pentaho.com/browse/BACKLOG-30731
=> [BACKLOG-30638][BACKLOG-30731] Parquet In/Out support with S3/HCP

common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/format/HadoopFormatBase.java, common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroInputFormat.java, common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/format/orc/PentahoOrcInputFormat.java, common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/format/orc/PentahoOrcRecordReader.java, common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/format/parquet/delegate/apache/PentahoApacheInputFormat.java, common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/format/parquet/delegate/twitter/PentahoTwitterInputFormat.java, common-fragment-V1/src/test/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroInputFormatTest.java, common-fragment-V1/src/test/java/org/pentaho/hadoop/shim/common/format/orc/PentahoOrcInputFormatTest.java, common-fragment-V1/src/test/java/org/pentaho/hadoop/shim/common/format/orc/PentahoOrcReadWriteTest.java, common-fragment-V1/src/test/java/org/pentaho/hadoop/shim/common/format/parquet/PentahoParquetInputFormatTest.java, shim-api/src/main/java/org/pentaho/hadoop/shim/api/format/IPentahoInputFormat.java, shim-api/src/main/java/org/pentaho/hadoop/shim/api/format/IPentahoOrcInputFormat.java
PentahoOrcInputFormat can now work without a named cluster defined.
This commit also includes general cleanup and de-duplication.
https://jira.pentaho.com/browse/BACKLOG-30732
https://jira.pentaho.com/browse/BACKLOG-30639
=> [BACKLOG-30732][BACKLOG-30639] Orc Input/Output with no named cluster

common-fragment-V1/src/main/java/org/pentaho/big/data/impl/shim/HadoopClientServicesImpl.java
exported are Avro format.  No way to specify this via the gui/command
line, so always include the avro jars on export.
=> [BACKLOG-32217] Avro jar files are needed on export if the files to be

shims/cdh61/driver/pom.xml, shims/emr521/driver/pom.xml, shims/hdp30/driver/pom.xml
=> [BACKLOG-31428] Do not bundle jars that should be pulled from the main

common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/CommonHadoopShim.java
reasonable; default is 45 times with 20 second timeouts.  Reduced to 5
retries.
=> [BACKLOG-32812] Reduce client connection retries to something more

shims/apache/driver/src/main/java/org/pentaho/hadoop/shim/pvfs/PvfsHadoopBridge.java, shims/apache/driver/src/test/java/org/pentaho/hadoop/shim/pvfs/PvfsHadoopBridgeTest.java
when writing Parquet and Orc files to S3 bucket
Formerly used URI.getHost() to determine the vfs conn name,
which fails if there are spaces or special chars in the name.
Switched to the method used elsewhere for pvfs
(ConnectionFileNameParser)
https://jira.pentaho.com/browse/PDI-18615
=> [PDI-18615] Could not find named connection null

shims/dataproc1421/pom.xml
Upgrade Avro version from 1.7.7 to 1.8.1 for Executing Sqoop on GDP
=> [BACKLOG-33827] Upgrade Avro version from 1.7.7 to 1.8.1 

shims/dataproc1421/driver/pom.xml
Included hbase-mapreduce dependency for dataproc big data shim
=> [BACKLOG-33822] - Added hbase-mapreduce dependency for GDP

shims/apache/driver/pom.xml, shims/apache/driver/src/main/java/org/pentaho/hadoop/shim/pvfs/PvfsHadoopBridge.java, shims/apache/driver/src/main/java/org/pentaho/hadoop/shim/pvfs/conf/GcsConf.java, shims/apache/driver/src/test/java/org/pentaho/hadoop/shim/pvfs/conf/GcsConfTest.java
Add support to read and write Parquet and ORC files from Google Cloud Storage Bucket in PDI client.
=> [BACKLOG-33529] Support for Parquet and ORC GCS read and write operations

common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/ShimConfigsLoader.java, common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/ConfigurationProxyV2.java
creating a Configuration object.
=> [BACKLOG-34197] Process system variables in config.properties when

shims/dataproc1421/driver/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Update the dataproc version to 1.4.
This change only applies to the version shown in the UI dropdown when creating a new hadoop cluster.
The driver version, kar filename etc would still continue to have 1.4.21 in them.
=> [BACKLOG-34161] Update dataproc UI version to 1.4 from 1.4.21

mapreduce/src/test/java/org/pentaho/hadoop/mapreduce/PentahoMapReduceTest.java
on resources in the unit test folder that weren't being copied into the
it-classes dir at build time.  Easy fix is to make the IT a unit test;
doesn't take so long to run that it needed to be in IT in the first
place.
=> [TEST] IT test living in the unit test folder; failed because it relied

common-fragment-V1/src/test/java/org/pentaho/big/data/impl/shim/mapreduce/PentahoMapReduceJobBuilderImplTest.java
Method to get property was changed in [BACKLOG-35618], from "getOrDefault" to "get" and the test was mocking the "getOrDefault" method
=> BACKLOG-35760 - Address failing tests in big-data-hadoop-shims-common

shims/cdh61/driver/pom.xml, shims/cdpdc71/driver/pom.xml, shims/dataproc1421/driver/pom.xml, shims/emr521/driver/pom.xml, shims/hdi40/driver/pom.xml, shims/hdp30/driver/pom.xml
up by log4j classes.
This commit is a cherry-pick from master 6b64860
=> [BACKLOG-35743] Exclude slf4j dependencies to ensure logging gets picked

shims/apache/driver/pom.xml
Reverts pentaho/pentaho-hadoop-shims#1346
Inadvertantly pushed into 9.4 instead of master, so reverting
=> Revert "[PPP-4789] Updated Vulnerable Component: commons-text"

shims/apache/driver/pom.xml, shims/cdh61/driver/pom.xml, shims/cdpdc71/driver/pom.xml, shims/dataproc1421/driver/pom.xml, shims/emr521/driver/pom.xml, shims/hdi40/driver/pom.xml, shims/hdp30/driver/pom.xml, shims/mapr60/driver/pom.xml, shims/mapr61/driver/pom.xml, shims/pom.xml
assumes the required JVM is the highest in the package, which is not the case.
=> [BACKLOG-39454] Bundle plugin is confused by multi-version jar files and

shims/apachevanilla/driver/pom.xml, shims/apachevanilla/driver/src/main/resources/OSGI-INF/blueprint/blueprint.xml, shims/apachevanilla/pmr/assembly.xml
[BACKLOG-41186] - Display both cdpdc71 and ApacheVanilla shim in Hadoop Cluster Dialog box drop down
[BACKLOG-41186]: https://hv-eng.atlassian.net/browse/BACKLOG-41186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-41186] - Display both cdpdc71 and ApacheVanilla shim in Hadoop Cluster Dialog box drop down

shims/apache/driver/pom.xml, shims/apachevanilla/driver/pom.xml, shims/cdpdc71/driver/pom.xml, shims/dataproc1421/driver/pom.xml, shims/dataproc1421/pom.xml
PR Set for https://hv-eng.atlassian.net/browse/PPP-4582:
- https://github.com/pentaho/pdi-plugins-ee/pull/1290
- https://github.com/pentaho/pentaho-platform/pull/5676
- https://github.com/pentaho/pentaho-hadoop-shims/pull/1452
Updated the gcs-connector versions to 3.0.2 where possible; it doesn't include gooogle-oauth-client at all.
- I had to add gcsio for apache driver so that it can be used in GcsConf for import com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem;
Dataproc1421 is stuck on Hadoop 2, so, we have to go with hadoop2-2.2.24 version, which has vulnerabilities pertaining to Hadoop 2.
All remaining instances of google oauth (including that from gcs-connector:jar:hadoop2-2.2.24 → google-oauth-client:jar:1.34.1) are now on 1.33.3+, whose indirect vulnerabilities pertain …
=> [PPP-4582] Use of Vulnerable Component: Components/oauth_client_library_for_java

shims/apachevanilla/driver/pom.xml
**Addressing this issue**: https://hv-eng.atlassian.net/browse/BACKLOG-42260
- By Upgrading Hadoop to 3.4.0 we can utilise the 3.0.2 version of gcs-connector which is the latest.
- This hadoop upgrade is a comprehensive upgrade which is tagged to https://hv-eng.atlassian.net/browse/BACKLOG-41761.
- For now, we are just upgrading to safest possible version of gcs-connector that gives us the capability to run hadoop services smoothly.
=> [PPP-4582] [BACKLOG-42260] Use of Vulnerable Component: Components/oauth_client_library_for_java

shims/pom.xml
Reverts pentaho/pentaho-hadoop-shims#1463
=> Revert "[BACKLOG-42279] Remove obsolete shim drivers for 10.2.0.1 build pipel…"

shims/apache/driver/pom.xml, shims/apachevanilla/driver/pom.xml, shims/cdpdc71/driver/pom.xml, shims/emr700/driver/pom.xml
The newer jetty-runner version includes some slf4j stuff that causes excessive debug logs when using parquet files. This reverts to an older version that shouldn't be vulnerable (at least according to maven central)
=> [PPP-5035][BACKLOG-42242] Revert jetty-runner version

shims/apache/driver/pom.xml
Accidentally changed the version on `jetty-rewrite` instead of `jetty-runner` for the apache driver. Fix for that.
=> [PPP-5035] fix incorrect jetty artifact version

common-dependencies-V1/pom.xml, common-fragment-V1/pom.xml, shims/apache/driver/pom.xml, shims/apache/kar/pom.xml
This PR replaces [pentaho-hadoop-shims#1483](https://github.com/pentaho/pentaho-hadoop-shims/pull/1483) as I couldn't update it directly.
The extra commit solves:
- the existence of two 'exclusions' groups on a dependency tab group
- the repetition of an 'exclusion' on a resolverFilter tab group
@rmansoor @pentaho/tatooine_dev
=> [SP-6610] Backport of PPP-5166 - Use of Vulnerable Component: Components/jackson-databind 2.14.2 (Non OSGi upgrade)

shims/emr700/driver/pom.xml
Backport of https://hv-eng.atlassian.net/browse/BAD-1955
=> [SP-6611] Backport of BAD-1955 - [Bigdata] ORC input/output steps, falling when connected to EMR cluster (10.2 Suite)

shims/apache/driver/pom.xml
- [PPP-4895] Exclude jettison in shims/apache/driver/pom.xml
[PPP-4895]: https://hv-eng.atlassian.net/browse/PPP-4895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SP-6635] Backport of PPP-4895 - Vulnerable Component: Jettison

shims/apachevanilla/driver/pom.xml
Added the missing library which failing to read input data in hdfs input step
**Error details:**
DestHost:destPort hadoopavs.orl.eng.hitachivantara.com:9000 , LocalHost:localPort hadoopavs/10.177.176.195:0. Failed on local exception: java.io.IOException: Couldn't set up IO streams: java.lang.NoClassDefFoundError: org/apache/commons/codec/binary/Base64
=> [BACKLOG-42957] - [Bigdata] PMR Job is failing with ApacheVanilla Shim

shims/cdpdc71/driver/pom.xml
remove extra jetty version, go back to using the version from the parent poms. It was already this way on master, I think this was because of some backport/branching weirdness around 10.2.0.1 and master
=> [SP-6694] Remove extra jetty version in cdpdc71 driver

shims/apache/driver/pom.xml
- Exclude what is coming from org.apache.hadoop:hadoop-common
- Ensure the wanted version is used
- Ensure the artefacts are included on the final result
For PPP-5605
=> build: upgrade curator-client from 5.2.0 to 5.6.0

shims/apachevanilla/driver/pom.xml, shims/dataproc1421/driver/pom.xml
For dataproc1421 and apachevanilla:
- use the default jetty version for org.eclipse.jetty.websocket groupId
@pentaho/tatooine_dev
=> [PPP-5585] Vulnerable Component: Jetty (deep scan)

common-fragment-V1/pom.xml, pom.xml, shims/apache/driver/pom.xml, shims/apachevanilla/driver/pom.xml, shims/cdh61/driver/pom.xml, shims/cdpdc71/driver/pom.xml, shims/dataproc1421/driver/pom.xml, shims/emr700/driver/pom.xml, shims/emr770/driver/pom.xml, shims/hdi40/driver/pom.xml
This pull request introduces changes to multiple `pom.xml` files across various modules to update dependencies and align versioning. The key updates include adding a new test dependency in one module and replacing the `jetty.version` property with `jetty-hadoop.version` for Jetty dependencies in several modules.
* Added `jakarta.servlet-api` as a test dependency in the `common-fragment-V1/pom.xml` file. This ensures compatibility with Jakarta Servlet APIs during testing.
* Updated Jetty dependencies in the following modules to use the `jetty-hadoop.version` property instead of `jetty.version`:
- `shims/apache/driver/pom.xml` [[1]](diffhunk://#diff-40c0b80627f3a69386cedc49c7cd0bed5ae3e456ad48416d7df52ffbb51e1c49L42-R60) [[2]](diffhunk://#diff-40c0b80627f3a69386cedc49c7cd0bed5ae3e456ad48416d …
=> [BACKLOG-40823] - Upgrade the Tomcat version from current to 10.x.x with Java 17 

common-fragment-V1/pom.xml, shims/apache/driver/src/main/java/org/pentaho/hadoop/shim/pvfs/conf/S3Conf.java
**Causes:**
The issue is due to [this function](https://github.com/pentaho/pentaho-hadoop-shims/blob/eccfd2edb4ed00beb6e37c99d00a58302b3c8299/common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/format/HadoopFormatBase.java#L27) changing from the thread classloader to the class’s classloader. The function then performs an action that, in the case exposed in [BAD-1967](https://hv-eng.atlassian.net/browse/BAD-1967), will eventually call some cache access functions that expect specific dependencies that were only accessible in the thread classloader, and are now are missing. This matches the original design for the big data stuff, which was to be able to have multiple big data drivers active at once, each with its own collection of dependencies.  So, setting the classloader from …
=> fix[BAD-1967]: include httpcore and httpclient dependencies in the common fragment

common-fragment-V1/pom.xml, shims/apache/driver/src/main/java/org/pentaho/hadoop/shim/pvfs/conf/S3Conf.java
Original PRs: https://github.com/pentaho/pentaho-hadoop-shims/pull/1643, https://github.com/pentaho/pentaho-hadoop-shims/pull/1644, https://github.com/pentaho/pentaho-hadoop-shims/pull/1645
=> fix[SP-6904]: include httpcore and httpclient dependencies in the common fragment
