hive-jdbc/src/org/apache/hadoop/hive/jdbc/HiveDriver.java
hive-jdbc/src/org/apache/hive/jdbc/HiveDriver.java
hive-jdbc/src/org/apache/hive/jdbc/ImpalaDriver.java
hive-jdbc/test-src/org/apache/hadoop/hive/jdbc/HiveDriverTest.java
hive-jdbc/test-src/org/apache/hive/jdbc/HiveDriverTest.java
hive-jdbc/test-src/org/apache/hive/jdbc/ImpalaDriverTest.java

Backport of #192 to the 5.3 branch

[PDI-13407]: Fixed error in Hive/Impala drivers during connect / getActiveDriver()

---

mapr401/src/org/pentaho/hadoop/shim/mapr401/ConfigurationProxyV2.java

* Added list of missed resources.
* The main reason was in using local value, but not the current one, of UserGroupInformation which is set on Configuration object creation.

[BAD-168] Mapr401: When using impersonation, proxy user is not picked for MapReduce operations

---

common/test-src/org/pentaho/hadoop/shim/common/CommonPigShimTest.java

* Abstract CommonPigShim to TestPigShim
* Reformat

[TEST] CommonPigShim is Abstract

---

mapr31/package-res/config.properties

@mattyb149, would you mind review/merge

SP-1719 - backport for PDI-12886- PDI Sqoop Jobs fail when SQOOP_HOME is defined 

---

mapr401/src/org/pentaho/hadoop/shim/mapr401/ConfigurationProxyV2.java

Backport from https://github.com/pentaho/pentaho-hadoop-shims/pull/194

[BAD-168][5.3] Mapr401: When using impersonation, proxy user is not picked for MapReduce operations

---

common/src/org/pentaho/hadoop/shim/common/DriverProxyInvocationChain.java
common/src/org/pentaho/hadoop/shim/common/HiveSQLUtils.java
common/test-src/org/pentaho/hadoop/shim/common/HiveSQLUtilsTest.java

Made a change to modify insert sql strings which are generated by Database class:
* add TABLE keyword;
* remove column names.

[BAD-172] - INSERT into a table does not work for Hive 0.14

---

mapr401/ivy.xml

Added required test dependencies.
Test-sources successfully compiled. But not all tests finished successfully - some of them seems to be related to Unix file system. Not sure about others - if needed next pull-request would be done.

[TEST][MAPR401] Added test dependencies.

---

build.xml

- To fix CI job running through project root with continuous target

[TEST] - pentaho-hadoop-shims continuous problem

---

build.xml
common/test-src/org/pentaho/hadoop/shim/common/CommonPigShimTest.java
hdp21/ivy.xml
hdp22/ivy.xml
idh23/build.properties
mapr401/ivy.xml

[TEST] -test and build related problems, fixed in master, backported

---

build.xml

Added emr shim to build modules list

[BAD-219] - Support for all BD services on EMR Hadoop tech

---

api/test-src/org/pentaho/hadoop/shim/HadoopConfigurationLocatorTest.java
cdh53/test-src/org/pentaho/hadoop/shim/cdh53/ShimRegistrationTest.java
emr32/test-src/org/pentaho/hadoop/shim/emr32/ShimRegistrationTest.java
hdp21/test-src/org/pentaho/hadoop/shim/hdp21/ShimRegistrationTest.java
hdp22/test-src/org/pentaho/hadoop/shim/hdp22/ShimRegistrationTest.java
hive-jdbc/test-src/org/pentaho/hadoop/hive/jdbc/HadoopConfigurationUtilTest.java
mapr31/test-src/org/pentaho/hadoop/shim/mapr31/ShimRegistrationTest.java
mapr31/test-src/org/pentaho/hadoop/shim/mapr31/authentication/PropertyAuthenticationProviderParserTest.java
mapr401/test-src/org/pentaho/hadoop/shim/mapr401/ShimRegistrationTest.java
mapr401/test-src/org/pentaho/hadoop/shim/mapr401/authentication/PropertyAuthenticationProviderParserTest.java

Tests are modified to reflect code changes.

[TEST] - Fix failures

---

mapr401/build.properties
mapr401/build.xml
mapr401/ivy.xml

Updated build.xml and ivy.xml.

[BAD-257] - MapR401: PDI fails to load when mapr401 shim is set active

---

common/src-mapred/org/pentaho/hbase/mapred/PentahoTableInputFormat.java

Added logic to append specific-timestamp and timestamp-range filtering settings to HBase Table Reader

[PDI-13546] PMR HBase Timestamp Filtering

---

common/src/org/pentaho/hbase/shim/common/CommonHBaseConnection.java
emr34/src/org/pentaho/hbase/shim/emr34/HBaseConnectionImpl.java
emr34/test-src/org/pentaho/hbase/shim/emr34/HBaseConnectionImplTest.java

* Added unit test
* Removed unnecessary override
* Changed classname separator for inner class

[BACKLOG-3253] - HBase Input fails if Filter condition is specified

---

api/test-src/org/pentaho/hadoop/shim/HadoopConfigurationLocatorTest.java
cdh53/test-src/org/pentaho/hadoop/shim/cdh53/ShimRegistrationTest.java
hdp21/test-src/org/pentaho/hadoop/shim/hdp21/ShimRegistrationTest.java
hdp22/test-src/org/pentaho/hadoop/shim/hdp22/ShimRegistrationTest.java
hive-jdbc/test-src/org/pentaho/hadoop/hive/jdbc/HadoopConfigurationUtilTest.java
mapr31/test-src/org/pentaho/hadoop/shim/mapr31/ShimRegistrationTest.java
mapr31/test-src/org/pentaho/hadoop/shim/mapr31/authentication/PropertyAuthenticationProviderParserTest.java
mapr401/test-src/org/pentaho/hadoop/shim/mapr401/ShimRegistrationTest.java
mapr401/test-src/org/pentaho/hadoop/shim/mapr401/authentication/PropertyAuthenticationProviderParserTest.java

this is simply a backport of what was fixed in master and 5.4
this will not fix all the unit tests. some failures are still being investigated.
@lucboudreau @mattyb149 please take a look if time permits

[TEST] - Fix failures - backport to 5.3

---

mapr401/ivy.xml

Moved hbase libs from PMR folder.

[PDI-13881] - MAPR401: PMR jobs are failing against kerberized cluster

---

mapr410/build.properties
mapr410/ivy.xml
mapr410/src/org/pentaho/hadoop/shim/mapr410/SnappyShim.java

[BAD-318] Hadoop File Output/Input steps fail to output to HDFS with Hadoop-snappy compression

---

emr34/ivy.xml

This seems to fix compilation issue in EMR

[BUILD-FAIL] Added dependency for API module

---

build.xml
cdh54/build.properties
common-shims-build.xml
common/test-src/org/pentaho/hadoop/shim/common/DriverProxyInvocationChainTest.java
emr34/ivy.xml

Deleted ../api/dist usage.
Fixed two unit tests failures due to incorrect ivy.config

[BUILD-FAIL] Force to use dependency for API module (Do not use local api/dist).

---

common/src/org/pentaho/hbase/shim/common/CommonHBaseConnection.java

otherwise that's going to be hard for QA to verify
@brosander please, sir.

[BAD-312] - add logging to make open/close HBase connection events visible

---

common/src/org/pentaho/hadoop/shim/common/DriverProxyInvocationChain.java
common/src/org/pentaho/hadoop/shim/common/HiveSQLUtils.java
common/test-src/org/pentaho/hadoop/shim/common/DriverProxyInvocationChainTest.java
common/test-src/org/pentaho/hadoop/shim/common/HiveSQLUtilsTest.java

Select database after connection was established https://issues.apache.org/jira/browse/HIVE-4256
@mattyb149 @brosander

[BAD-157] Impala: Unable to connect to other than "default" schema using Impala connection template

---

idh23/build.properties
idh23/ivy.xml

with those maintained by the build team.
@lucboudreau @lgrill-pentaho

[CLEANUP] making version properties consistent

---

cdh54/src/org/pentaho/hadoop/shim/cdh54/HadoopShim.java

- Removed incorrect override in CDH54 shim

[BAD-215] Add Support for the Simba Driver

---

api/ivy.xml

!! Do not merge until we get the official go-ahead for VFS2.1.

Upgrade to vfs2.1

---

cdh54/src/org/pentaho/hadoop/shim/cdh54/HadoopShim.java

Related https://github.com/pentaho/big-data-plugin/pull/459

[BAD-332] - renamed default driver name to be used Cloudera one.

---

emr34/package-res/config.properties

[BAD-339] emr34: Update EMR friendly name from Amazon EMR 3.2 to Amzon EMR 3.4

---

api/src/org/pentaho/hbase/shim/api/ColumnFilter.java
api/src/org/pentaho/hbase/shim/api/Mapping.java
common/src/org/pentaho/hbase/shim/common/CommonHBaseConnection.java

* Added possibility to create filters for Key field and for Tupple Mapping
* Added StartsFrom operator

[PDI-9392] HBase input step filter column family by prefix

---

cdh54/ivy.xml
hdp22/ivy.xml

Exclude duplicate jars from client configuration.

[PDI-13506] - Duplicate Jars in Shims

---

cdh54/ivy.xml

Exclude duplicate jars from client configuration.

[PDI-13506] - exclude more jars

---

emr310/ivy.xml

(cherry picked from commit bfa6471)

[BAD-398] - Removed amazon classifiers

---

common/src/org/pentaho/hadoop/shim/common/CommonHadoopShim.java
common/test-src/org/pentaho/hadoop/shim/common/CommonHadoopShimTest.java

2 commits: fix + checkstyle
@brosander could you please review

[BAD-358] - Unable to finish successfully Sqoop job when cluster in HA mode.

---

emr41/ivy.xml

(cherry picked from commit e1f6969)

[BAD-434] Update / Remove commons-collections for EMR 4.1 Shim

---

hdp23/ivy.xml

[BAD-420] - Perform removal/upgrade of commons-collections library to 3.2.2

---

hive-jdbc/src/org/apache/hive/jdbc/HiveSimbaDriver.java
hive-jdbc/src/org/apache/hive/jdbc/ImpalaSimbaDriver.java
hive-jdbc/test-src/org/apache/hive/jdbc/HiveDriverTest.java
hive-jdbc/test-src/org/apache/hive/jdbc/ImpalaSimbaDriverTest.java

* Added check for not trying to connect hive on impala URL
* Added tests

[BAD-394] - Misleading error message is shown if Cloudera Simba connection is not defined properly

---

api/ivy.xml
cdh51/ivy.xml
cdh52/ivy.xml
cdh53/ivy.xml
cdh54/ivy.xml
common-shims-build.xml
common/src/org/pentaho/hbase/shim/common/CommonHBaseConnection.java
common/src/org/pentaho/hbase/shim/common/messages/messages_en_US.properties
common/test-src-hadoop-shim-1.0/README.MD
common/test-src-hadoop-shim-1.1/README.MD
common/test-src-hbase-shim-1.0/org/pentaho/hbase/shim/common/CommonHBaseConnectionTest.java
common/test-src-hbase-shim-1.1/org/pentaho/hbase/shim/common/CommonHBaseConnectionTest.java
common/test-src-pig-shim-1.0/README.MD
common/test-src-pig-shim-1.1/README.MD
common/test-src/org/pentaho/hadoop/shim/common/ConfigurationProxyTest.java
common/test-src/org/pentaho/hbase/shim/common/CommonHBaseBytesUtilTest.java
emr310/ivy.xml
emr34/ivy.xml
emr41/ivy.xml
hdp21/ivy.xml
hdp22/ivy.xml
hdp23/ivy.xml
hive-jdbc/ivy.xml
mapr31/ivy.xml
mapr401/ivy.xml
mapr410/ivy.xml

[BAD-443] - Increase unit test coverage in SHIM codeline

---

common/src-hbase-1.0/org/pentaho/hadoop/hbase/factory/HBase10ClientFactory.java

Opening access to HBase10ClientFactory to allow extension outside of
the package.  This will allow a HBase10ImpersonatingClientFactory
implementation which supports secure impersonation.
@brosander

[BACKLOG-7514] Support for HBase impersonation

---

common/src/org/pentaho/hadoop/shim/common/DriverProxyInvocationChain.java
common/test-src/org/pentaho/hadoop/shim/common/DriverProxyInvocationChainTest.java

Problem with the way of retrieving list of the tables.
* Current versions of the hive and impala has implemented method getTables - so logic changed to the firstly attempt to use origin method than in case of misbehavior switch to the old one which uses thrift client
* Upgraded query from "show tables" -> "show tables in <schemaName>" in case of schema name != null;
* Workaround with dbname in connection string was improved: currently not only "use <dbname>" on connection phase is used, but also setting dbname from url into the 'hivevar' space (session/connection scope). Then in case of the need to manipulate of the objects from other schemas we can switch to them and after return back by switching into original connection <dbname>
*  `'use ${hiveconf:pentaho.current.dbname}'`
* The same …

[PMD-1004] - PME: Import table command retrieves invalid tables on Hive2 and Impala JDBC connections

---

api/test-src/org/pentaho/hbase/shim/api/HBaseValueMetaTest.java
api/test-src/org/pentaho/hbase/shim/spi/MockHBaseByteConverterUsingJavaByteBuffer.java

increased test coverage according to BACKLOG-7097 for HBaseValueMetaTest

[BACKLOG-7097] increase coverage HBaseValueMetaTest

---

api/src/org/pentaho/hadoop/shim/HadoopConfigurationLocator.java

* Added more info into exception

[BAD-531] - Need more detailed message on failing HadoopConfigurationLocator loadHadoopConfiguration method invoke

---

common/src/org/pentaho/hadoop/shim/common/DriverProxyInvocationChain.java
common/test-src/org/pentaho/hadoop/shim/common/DriverProxyInvocationChainTest.java

Removed set variables functionality as it still is not working for impala ( https://issues.cloudera.org/browse/IMPALA-3851 )

[BACKLOG-9073]-Syntax error when connecting to Impala

---

common/src/org/pentaho/hadoop/shim/common/CommonHadoopShim.java

* Added impala to map of the drivers

[BACKLOG-9547]-[DEV]-Update the impersonation code to add impersonating impala driver to the map of loaded drivers

---

common-shims-build.xml

[ENGOPS-2277] Coverage fix for ce shims

---

cdh57/ivy.xml
cdh58/ivy.xml

[PPP-3571] Use of vulnerable component httpclient-4.2.5.jar - CVE-2014-3577

---

cdh57/ivy.xml
cdh58/ivy.xml

[SP-3006] Backport of PPP-3571 - Use of vulnerable component httpclient-4.2.5.jar - CVE-2014-3577 (7.0 Suite)

---

cdh57/ivy.xml
cdh58/ivy.xml

[SP-3007] Backport of PPP-3571 - Use of vulnerable component httpclient-4.2.5.jar - CVE-2014-3577 (6.1 Suite)

---

cdh57/ivy.xml
cdh58/ivy.xml

Reverts pentaho/pentaho-hadoop-shims#410

Revert "[SP-3007] Backport of PPP-3571 - Use of vulnerable component httpclient-4.2.5.jar - CVE-2014-3577 (6.1 Suite)"

---

cdh58/ivy.xml

Revert: [PPP-3571] Use of vulnerable component httpclient-4.2.5.jar - CVE-2014-3577

---

cdh57/ivy.xml
cdh58/ivy.xml
cdh59/ivy.xml

Reverts pentaho/pentaho-hadoop-shims#409

Revert "[SP-3006] Backport of PPP-3571 - Use of vulnerable component httpclient-4.2.5.jar - CVE-2014-3577 (7.0 Suite)"

---

common/common-shim/src/test/java/org/pentaho/hadoop/mapreduce/GenericTransCombinerTest.java
common/common-shim/src/test/java/org/pentaho/hadoop/mapreduce/GenericTransReduceTest.java
common/common-shim/src/test/java/org/pentaho/hadoop/mapreduce/MRTestUtil.java
common/common-shim/src/test/java/org/pentaho/hadoop/mapreduce/PentahoMapReduceIT.java
common/common-shim/src/test/java/org/pentaho/hadoop/mapreduce/PentahoMapRunnableTest.java
common/common-shim/src/test/java/org/pentaho/hadoop/mapreduce/test/MRUtilTest.java

These tests were failed for the case when there is not empty c:\Users\<USER>\.kettle\db.cache-XXX file.
Fixed.

[BAD-601]: The bunch of unit tests for pentaho-hadoop-shims (master branch) are failed on windows

---

pom.xml
shims/cdh510/assemblies/cdh510-shim/pom.xml
shims/cdh59/assemblies/cdh59-shim/pom.xml
shims/emr46/assemblies/emr46-shim/pom.xml
shims/emr52/assemblies/emr52-shim/pom.xml
shims/hdi35/assemblies/hdi35-shim/pom.xml
shims/hdp24/assemblies/hdp24-shim/pom.xml
shims/hdp25/assemblies/hdp25-shim/pom.xml
shims/mapr510/assemblies/mapr510-shim/pom.xml
shims/mapr520/assemblies/mapr520-shim/pom.xml

[ENGOPS-3050] added eula wrap to shim zips

---

shims/cdh511/pom.xml
shims/emr531/pom.xml
shims/hdi35/pom.xml
shims/hdp26/pom.xml
shims/mapr520/pom.xml

fix order of module list build

[BAD-677]-change order of building modules

---

shims/pom.xml

@lgrill-pentaho @VasilinaTerehova 
required for singular shim release without direct root pom modification

[ENGOPS-3274] put shim modules in profiles

---

common/modern/src/main/java/org/pentaho/hadoop/shim/common/authorization/AuthenticatingHadoopShim.java

Updated onLoad method for unit-tests in ee shims.
Merge this pull request before https://github.com/pentaho/pentaho-big-data-ee/pull/224

[BAD-861]-exclude .installedLicense dependence for unit tests for pentaho-big-data-ee

---

shims/cdh510/assemblies/cdh510-shim/src/assembly/assembly.xml

BAD-885-For cdh510 shim remove jasper-compile, jasper-runtime from lib folder assembly

---

pom.xml
shims/pom.xml

@VasilinaTerehova @lgrill-pentaho

[ENGOPS-3487] added profile activations for api & shims

---

shims/emr58/assemblies/default/src/assembly/assembly.xml

@alexzhk please view and merge

[BAD-985] - Develop and DEV Validate the EMR 5.8 Shim against Pentaho8.0 (Master) CE/Unsecured cluster

---

shims/hdp25/assemblies/hdp25-shim/src/main/resources/config.properties
shims/hdp26/assemblies/hdp26-shim/src/main/resources/config.properties

@VasilinaTerehova please take a view and merge

[BAD-831] - It's impossible to use simultaneosly drivers for Hive 2 & Spark SQL in hdp sec/unsec in Ubuntu

---

common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/AvroSchemaConverter.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroOutputFormat.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroRecordWriter.java

-Avro content generator now uses the default value when generating content for a column which does not have any data.
-Converts other data types to avro data type.
-Enable renaming of a column in avro schema..
-Enable removing of columns from the avro schema

[BACKLOG-18641] - Updated Avro output generator to resolve issues

---

common/common-shim/pom.xml
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroRecordWriter.java

Reverts pentaho/pentaho-hadoop-shims#548

Revert "[BACKLOG-18641] - Properly storing date columns in avro date format"

---

common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/AvroSchemaConverter.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroOutputFormat.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroRecordWriter.java

Reverts pentaho/pentaho-hadoop-shims#547

Revert "[BACKLOG-18641] - Updated Avro output generator to resolve issues"

---

common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/AvroSchemaConverter.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroOutputFormat.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroRecordWriter.java

Reverts pentaho/pentaho-hadoop-shims#550

Revert "Revert "[BACKLOG-18641] - Updated Avro output generator to resolve issues""

---

common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/AvroSchemaConverter.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroOutputFormat.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroRecordWriter.java

Reverts pentaho/pentaho-hadoop-shims#551

Revert "Revert "Revert "[BACKLOG-18641] - Updated Avro output generator to resolve issues"""

---

shims/cdh511/impl/pom.xml
shims/cdh512/impl/pom.xml
shims/emr56/impl/pom.xml
shims/emr58/impl/pom.xml
shims/mapr510/impl/pom.xml
shims/mapr520/impl/pom.xml

@pentaho/2-1b @VasilinaTerehova pls review

[BACKLOG-18699] update vulnerable component xstream

---

common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/PentahoParquetInputFormat.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/PentahoParquetOutputFormat.java
common/common-shim/src/test/java/org/pentaho/hadoop/shim/common/format/PentahoParquetInputFormatTest.java
common/common-shim/src/test/java/org/pentaho/hadoop/shim/common/format/PentahoParquetOutputFormatTest.java

This reverts commit 88d2bbf5d331c53cba258f7687ed401fae69cf58, reversing
changes made to 3d222c1897c786227a09477fc0c6c1c91b616e4b.
@mkambol / @flbrino / @aminmkhan

Revert "Merge pull request #602 from flbrino/BACKLOG-19435"

---

common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/parquet/PentahoParquetReadSupport.java
common/common-shim/src/test/java/org/pentaho/hadoop/shim/common/format/PentahoParquetInputFormatTest.java
common/common-shim/src/test/java/org/pentaho/hadoop/shim/common/format/parquet/PentahoParquetRecordReaderTest.java

https://github.com/pentaho/pentaho-hadoop-shims/pull/625

[BACKLOG-19493] Fix Parquet schema creation

---

api/src/main/java/org/pentaho/hadoop/shim/api/format/SchemaDescription.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/AvroConverter.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/AvroSchemaConverter.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroInputFormat.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroRecordReader.java
common/common-shim/src/test/java/org/pentaho/hadoop/shim/common/format/avro/AvroConverterFromAvroTest.java
common/common-shim/src/test/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroRecordReaderTest.java

- Adding some missed checkins from master

 [BACKLOG-19523] - Adding additional conversion logic for Avro Input

---

common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/AvroConverter.java

WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!

[ENGOPS-3650] change Pentaho to Hitachi Vantara and update copyright date

---

api/src/main/java/org/pentaho/hadoop/shim/api/format/IPentahoOrcOutputFormat.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/PentahoOrcOutputFormat.java

[BACKLOG-20030] ORC Output Step - Implement a working output step using format shim

---

common/pom.xml
pom.xml
shims/pom.xml

WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!

[ENGOPS-1757] version name consolidation

---

api/src/main/java/org/pentaho/hadoop/shim/api/format/IPentahoOrcOutputFormat.java
common/common-shim/pom.xml
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/CommonFormatShim.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/PentahoOrcOutputFormat.java
common/common-shim/src/test/java/org/pentaho/hadoop/shim/common/format/orc/PentahoOrcReadWriteTest.java
shims/hdp25/impl/pom.xml
shims/hdp26/assemblies/default/src/assembly/assembly.xml
shims/hdp26/default/pom.xml
shims/hdp26/impl/pom.xml
shims/hdp26/pom.xml

Adds the overwrite existing flag to the Orc Output Step.
Addresses issues with the Orc Output Step actually writing [BACKLOG-20030]

[BACKLOG-20291] Add overwrite existing flag in Orc Output step

---

common-services-api/cluster/pom.xml
common-services-api/clusterServiceLocator/pom.xml
common-services-api/hbase/pom.xml
common-services-api/mapreduce/pom.xml
common-services-api/pig/pom.xml
common-services-api/pom.xml

@lgrill-pentaho @VasilinaTerehova

[ENGOPS-3719] fix for metastore property

---

common-services-api/jdbc/pom.xml

@lgrill-pentaho @VasilinaTerehova

[ENGOPS-3719] more version property adjustments

---

common-services/pig/pom.xml

@lgrill-pentaho @VasilinaTerehova

[ENGOPS-3719] fix kettle-log4j-core version

---

shims/cdh513/common/pom.xml
shims/hdp26/common/pom.xml

@lgrill-pentaho @VasilinaTerehova

[ENGOPS-3719] fix more kettle-log4j-core versions

---

common-services-api/jdbc/pom.xml
pom.xml

[ENGOPS-3719] fix metastore-locator-api version

---

shims/cdh513/common/pom.xml
shims/cdh513/pom.xml

Moved orc to new karaf structure

[BACKLOG-20178]-Move parquet/avro/orc to karaf

---

common-services/mapreduce/src/test/java/org/pentaho/big/data/impl/shim/mapreduce/MapReduceJobBuilderImplTest.java
common-services/mapreduce/src/test/java/org/pentaho/big/data/impl/shim/mapreduce/MapReduceServiceFactoryImplTest.java
common-services/mapreduce/src/test/java/org/pentaho/big/data/impl/shim/mapreduce/MapReduceServiceImplTest.java
common-services/mapreduce/src/test/java/org/pentaho/big/data/impl/shim/mapreduce/PentahoMapReduceJobBuilderImplTest.java
common-services/oozie/src/test/java/org/pentaho/big/data/impl/shim/oozie/OozieServiceFactoryImplTest.java
common-services/pig/src/test/java/org/pentaho/big/data/impl/shim/pig/PigServiceFactoryImplTest.java
common-services/pig/src/test/java/org/pentaho/big/data/impl/shim/pig/PigServiceImplTest.java
common-services/sqoop/src/test/java/org/pentaho/big/data/impl/shim/sqoop/SqoopServiceFactoryImplTest.java
common-services/sqoop/src/test/java/org/pentaho/big/data/impl/shim/sqoop/SqoopServiceImplTest.java

mocks for services creation back
knox gateway checks should be reworked - todo in that places

[BACKLOG-20536]-fix unit tests the rest

---

common/common-shim/pom.xml
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/CommonFormatShim.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/orc/PentahoOrcInputFormat.java
pom.xml
shims/cdh511/pom.xml
shims/hdp26/assemblies/default/src/assembly/assembly.xml
shims/hdp26/pom.xml

[BACKLOG-20028] ORC Input Step - Implement a working input step using format shim

---

common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/PentahoOrcOutputFormat.java

[BACKLOG-20239] Update the UI and shims to write orc output file

---

shims/mapr520/impl/pom.xml
shims/mapr60/default/pom.xml
shims/mapr60/default/src/assembly/assembly.xml
shims/mapr60/impl/pom.xml
shims/mapr60/pom.xml

@VasilinaTerehova please take a view and merge

[BACKLOG-18942]-The tests of pentaho-hadoop-shims must be OS Independent

---

common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/AvroOutputField.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroInputFormat.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroOutputFormat.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroRecordReader.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroRecordWriter.java
common/common-shim/src/test/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroReadWriteTest.java

[BACKLOG-20721] [BACKLOG-20715] Read & write generic Avro files (non AEL)

---

common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroRecordReader.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroRecordWriter.java

[BACKLOG-21052] Fix the unit test for avro output and input (Only failing on wingman)

---

api/src/main/java/org/pentaho/hadoop/shim/api/format/AvroSpec.java
api/src/main/java/org/pentaho/hadoop/shim/api/format/IAvroOutputField.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/AvroOutputField.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroOutputFormat.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroRecordWriter.java

[BACKLOG-21076] Update the AvroOutput Dialog to support BigDecimal precision and scale.
[BACKLOG-21077] Update the shim to store and read data using decimal type with precision and scale

[BACKLOG-21076][BACKLOG-21077] Update the AvroOutput Dialog to support BigDecimal precision and scale.

---

api/src/main/java/org/pentaho/hadoop/shim/api/format/IAvroOutputField.java
common/common-shim/src/test/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroReadWriteTest.java

[BACKLOG-21077] Update the shim to store and read data using decimal type with precision and scale

---

common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroRecordWriter.java

[BACKLOG-21288] Avro Output fails on timestamp or date conversions.

---

common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroInputFormat.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroOutputFormat.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroRecordReader.java

[BACKLOG-21273] Avro logical types are not read and written correctly to the avro schema.

---

api/pom.xml
pom.xml

@VasilinaTerehova @Hramatskiu @cardosov

[BAD-1379] use proper version for platform-api

---

shims/emr511/assemblies/emr511-shim/src/main/resources/hbase-site.xml
shims/emr511/assemblies/emr511-shim/src/main/resources/hdfs-site.xml
shims/emr511/assemblies/emr511-shim/src/main/resources/hive-site.xml
shims/emr511/assemblies/emr511-shim/src/main/resources/mapred-site.xml
shims/emr511/assemblies/emr511-shim/src/main/resources/yarn-site.xml

@VasilinaTerehova please take a view and merge

[BAD-1424]-Some CE and EE shims contain different set of site files

---

shims/hdi35/impl/pom.xml

@VasilinaTerehova please take a view and merge

Fix shim tests for hdi 3.5 shim.

---

api/src/main/java/org/pentaho/hadoop/shim/api/format/AvroSpec.java
api/src/main/java/org/pentaho/hadoop/shim/api/format/IAvroInputField.java
api/src/main/java/org/pentaho/hadoop/shim/api/format/IAvroOutputField.java
api/src/main/java/org/pentaho/hadoop/shim/api/format/IFormatInputField.java
api/src/main/java/org/pentaho/hadoop/shim/api/format/IFormatOutputField.java
api/src/main/java/org/pentaho/hadoop/shim/api/format/IOrcInputField.java
api/src/main/java/org/pentaho/hadoop/shim/api/format/IOrcMetaData.java
api/src/main/java/org/pentaho/hadoop/shim/api/format/IOrcOutputField.java
api/src/main/java/org/pentaho/hadoop/shim/api/format/IPentahoOrcOutputFormat.java
api/src/main/java/org/pentaho/hadoop/shim/api/format/OrcSpec.java
common/common-shim/src/it/java/org/pentaho/hadoop/shim/common/CommonFormatShimTestIT.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/BaseFormatInputField.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/BaseFormatOutputField.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/PentahoOrcOutputFormat.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/AvroInputField.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/AvroOutputField.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroInputFormat.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroOutputFormat.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroRecordWriter.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/orc/OrcConverter.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/orc/OrcInputField.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/orc/OrcMetaDataReader.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/orc/OrcMetaDataWriter.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/orc/OrcOutputField.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/orc/OrcSchemaConverter.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/orc/PentahoOrcInputFormat.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/orc/PentahoOrcRecordReader.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/orc/PentahoOrcRecordWriter.java
common/common-shim/src/test/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroReadWriteTest.java
common/common-shim/src/test/java/org/pentaho/hadoop/shim/common/format/orc/PentahoOrcReadWriteTest.java

[BACKLOG-21444] Update the orc code to follow the changes done for avro
[BACKLOG-21426] Implement new Orc input structure using orc specification (non-ael)

[BACKLOG-21444][BACKLOG-21426] Feature Orc Input and Output

---

shims/mapr60/assemblies/mapr60-shim/src/main/resources/config.properties

@VasilinaTerehova please take a view

Fix mapr60 config properties file.

---

shims/hdp25/pom.xml
shims/hdp26/common/pom.xml
shims/hdp26/common/src/main/resources/OSGI-INF/blueprint/blueprint.xml
shims/hdp26/pom.xml

@pentaho/moseisley Please review along with the following additional pull requests:
https://github.com/pentaho/pentaho-big-data-ee/pull/300
https://github.com/pentaho/pentaho-yarn-kettle-plugin/pull/341

[BACKLOG-23342] - Enable HDP 2.6 secure shim within PDI

---

common-services-api/api/src/main/java/org/pentaho/hadoop/shim/api/ShimIdentifier.java
common-services-api/api/src/main/java/org/pentaho/hadoop/shim/spi/HadoopShim.java
common-services-api/api/src/main/java/org/pentaho/hadoop/shim/spi/ShimIdentifierInterface.java
common-services/hdfs/src/main/java/com/pentaho/big/data/bundles/impl/shim/hdfs/HadoopFileSystemFactoryImpl.java
shims/cdh513/common/src/main/resources/OSGI-INF/blueprint/blueprint.xml
shims/hdp26/common/src/main/resources/OSGI-INF/blueprint/blueprint.xml

[BACKLOG-24053] Add a shim identifier to the hdfs services.

---

shims/cdh513/common/pom.xml
shims/hdp26/common/pom.xml

Reverts pentaho/pentaho-hadoop-shims#793

Revert "[BACKLOG-24305] Duplicated classes in classpath"

---

shims/cdh513/common/pom.xml

[BACKLOG-24552] Removed duplicate api jars from cdh513/common

---

common-services-api/api/pom.xml
common-services-api/format/pom.xml
common-services-api/hbase/pom.xml
common-services-api/jdbc/pom.xml
common-services-api/mapreduce/pom.xml
common-services-api/oozie/pom.xml
common-services-api/pig/pom.xml
common-services-api/runtimeTest/pom.xml
shims/cdh513/common/pom.xml
shims/cdh513/hbase/pom.xml
shims/cdh513/hive/pom.xml
shims/cdh513/oozie/pom.xml
shims/cdh513/pom.xml
shims/cdh514/hbase/pom.xml
shims/cdh514/hive/pom.xml
shims/cdh514/oozie/pom.xml
shims/hdp25/common/pom.xml
shims/hdp25/hbase/pom.xml
shims/hdp25/hive/pom.xml
shims/hdp26/common/pom.xml
shims/hdp26/hbase/pom.xml
shims/hdp26/hive/pom.xml

Reverts pentaho/pentaho-hadoop-shims#800

Revert "[BACKLOG-24517] Adds explicit version numbers on exported packages. A…"

---

api/src/main/java/org/pentaho/hadoop/shim/api/format/ParquetSpec.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/parquet/ParquetConverter.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/parquet/PentahoParquetWriteSupport.java
common/common-shim/src/test/java/org/pentaho/hadoop/shim/common/format/parquet/PentahoParquetOutputFormatTest.java

[BACKLOG-24815] Parquet: Add support for INT96 (NON-AEL)

---

api/src/main/java/org/pentaho/hadoop/shim/api/format/IPentahoAvroInputFormat.java
common/common-shim/src/it/java/org/pentaho/hadoop/shim/common/CommonFormatShimTestIT.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/AvroInputField.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/AvroNestedReader.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/AvroNestedRecordReader.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroInputFormat.java

 [BACKLOG-24899] - Fix Avro integration tests after initial port of the legacy Avro Input step from 7.1.

---

api/src/main/java/org/pentaho/hadoop/shim/api/format/IPentahoAvroInputFormat.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/AvroNestedFieldGetter.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroInputFormat.java

[BACKLOG-25573] - Avro Input - Refactored to remove the dependency on the avro jar.

---

shims/hdp30/client/src/assembly/assembly.xml
shims/hdp30/pmr/pom.xml
shims/hdp30/pmr/src/assembly/assembly.xml
shims/hdp30/pom.xml

[BACKLOG-26036] - PMR Hadoop Input Output job hangs infinitely and does not fail out with an error

---

api/src/main/java/org/pentaho/hadoop/shim/api/format/IAvroInputField.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/AvroInputField.java

Moved indexes and keys to the index column
Made path column read only
Made index column editable

[BACKLOG-25986] - Moved indexes and keys to the index column

---

api/src/main/java/org/pentaho/hadoop/shim/api/format/IPentahoAvroInputFormat.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/AvroNestedReader.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/AvroNestedRecordReader.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/PentahoAvroInputFormat.java
common/common-shim/src/test/java/org/pentaho/hadoop/shim/common/format/avro/StreamingInputTest.java

[BACKLOG-25763] - Avro Input - Add support for reading JSON from a field.

---

shims/hdp30/default/pom.xml
shims/hdp30/pmr/pom.xml
shims/hdp30/pmr/src/assembly/assembly.xml
shims/hdp30/pom.xml

[BACKLOG-26277] Added missing libraries for the HBase Row Decoder Test for HDP 3.0

---

common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/AvroNestedRecordReader.java

Return the first row in an Avro datum.

[BACKLOG-26425] Return the first row in an Avro datum.

---

shims/hdp30/default/pom.xml
shims/hdp30/default/src/assembly/assembly.xml

@tkafalas @pentaho-svigneri @kcruzada

[BACKLOG-26433] - Added missing hive runtime dependencies.

---

shims/hdp30/assemblies/hdp30-shim/src/main/resources/config.properties

Fixed reference to hive jar in HDP30 shim.

[BACKLOG-26422] Fixed reference to hive jar in HDP30 shim.

---

shims/hdp26/common/pom.xml
shims/hdp26/common/src/main/resources/OSGI-INF/blueprint/blueprint.xml
shims/hdp26/hbase-comparators/pom.xml
shims/hdp26/pom.xml

Combined HDP26 CE shim into single jar (pentaho-hadoop-shims-hdp26-common)

[BACKLOG-26717] Combined HDP26 CE shim into single jar 

---

pom.xml
shims/hdp25/impl/pom.xml

This is a series of PRs, please see pentaho/maven-parent-poms#82 for full list.
@ssamora

[PPP-4226] Use of vulnerable component commons-compress  CVE-2018-11771

---

common-services/mapreduce/src/main/java/org/pentaho/big/data/impl/shim/mapreduce/PentahoMapReduceJobBuilderImpl.java
common/mapred/src/main/resources/org/pentaho/hadoop/mapreduce/messages/messages_en_US.properties

[BACKLOG-23920] - Fixed a metastore staging issue with Pentaho MapReduce.

---

common-dependencies/pom.xml
common-services-api/api/pom.xml
common-services-api/api/src/main/java/org/pentaho/hadoop/shim/ShimConfigsLoader.java
common-services/mapreduce/src/main/java/org/pentaho/big/data/impl/shim/mapreduce/PentahoMapReduceJobBuilderImpl.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/DistributedCacheUtilImpl.java

@pentaho/moseisley please review.

[BACKLOG-26856] - Enable Pentaho MapReduce for multiple shims concurrently.

---

shims/emr521/client/pom.xml
shims/emr521/client/src/assembly/assembly.xml

@tkafalas @lucboudreau Please review.

[BAD-1777] - Added missing dependencies for sqoop import with hbase using EMR 5.21.

---

api/pom.xml
common/common-hbase-comparators-api/pom.xml
common/common-shim/pom.xml
common/hadoop-shim/pom.xml
common/hbase-comparators/pom.xml
common/hbase/pom.xml
common/mapred/pom.xml
common/modern/pom.xml
common/pig-shim-1.0/pom.xml
common/pig-shim-1.1/pom.xml
common/pom.xml
pom.xml
shims/pom.xml

[CLEANUP] - updated versions

---

common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/format/avro/AvroNestedReader.java
common/common-shim/src/test/java/org/pentaho/hadoop/shim/common/format/avro/StreamingInputTest.java

avoid overwriting incoming data.

[BACKLOG-29507] Ensure a new array gets allocated for output data to

---

common/mapred/pom.xml
common/mapred/src/test/java/org/pentaho/hadoop/mapreduce/PentahoMapReduceIT.java
common/mapred/src/test/java/org/pentaho/hadoop/mapreduce/PentahoMapRunnableTest.java
common/pom.xml
pom.xml
shims/cdh512/impl/pom.xml
shims/cdh513/impl/pom.xml
shims/cdh514/impl/pom.xml
shims/cdh61/impl/pom.xml
shims/emr511/impl/pom.xml
shims/emr521/impl/pom.xml
shims/emr59/impl/pom.xml
shims/hdi35/impl/pom.xml
shims/hdp25/impl/pom.xml
shims/hdp26/impl/pom.xml
shims/hdp30/impl/pom.xml
shims/mapr520/impl/pom.xml
shims/mapr60/impl/pom.xml
shims/pom.xml

Fix for failing unit-test/IT tests caused by decoupling of constant step.

[BACKLOG-22188] Decouple constant step from Kettle engine

---

common/mapred/pom.xml
common/mapred/src/test/java/org/pentaho/hadoop/mapreduce/PentahoMapReduceIT.java
common/mapred/src/test/java/org/pentaho/hadoop/mapreduce/PentahoMapRunnableTest.java
common/pom.xml
pom.xml
shims/cdh512/impl/pom.xml
shims/cdh513/impl/pom.xml
shims/cdh514/impl/pom.xml
shims/cdh61/impl/pom.xml
shims/emr511/impl/pom.xml
shims/emr521/impl/pom.xml
shims/emr59/impl/pom.xml
shims/hdi35/impl/pom.xml
shims/hdp25/impl/pom.xml
shims/hdp26/impl/pom.xml
shims/hdp30/impl/pom.xml
shims/mapr520/impl/pom.xml
shims/mapr60/impl/pom.xml
shims/pom.xml

Reverts pentaho/pentaho-hadoop-shims#980 based on discussion on decoupling steps.

Revert "[BACKLOG-22188] Decouple constant step from Kettle engine"

---

api/pom.xml
shims/cdh513/impl/pom.xml
shims/cdh514/impl/pom.xml
shims/cdh61/impl/pom.xml
shims/emr511/impl/pom.xml
shims/emr521/impl/pom.xml
shims/hdi35/impl/pom.xml
shims/hdp25/impl/pom.xml
shims/hdp26/impl/pom.xml
shims/mapr520/impl/pom.xml
shims/mapr60/impl/pom.xml

@pentaho/tatooine @pentaho-lmartins @wseyler
* [PDI-17794] Removed version references due to maven-parent-poms controlling that aspect
* [PDI-17794] Removing dependencies due to being marked as unused and declared via dependency:analyze (shims/hdp25/impl/pom.xml, shims/cdh512/impl/pom.xml, shims/cdh513/impl/pom.xml,
shims/cdh514/impl/pom.xml, shims/cdh61/impl/pom.xml, shims/hdi35/impl/pom.xml)
This pull request is part of a series of pull requests:
- https://github.com/pentaho/maven-parent-poms/pull/137
- https://github.com/pentaho/adaptive-execution-layer/pull/3
- https://github.com/pentaho/big-data-plugin/pull/1682
- https://github.com/webdetails/cdf/pull/1075
- https://github.com/pentaho/commons-ee/pull/1
- https://github.com/webdetails/cpf/pull/144
- …

[PDI-17794] Warnings in Spoon console due to wrong version of log4j

---

common-fragment-V1/src/main/java/com/pentaho/big/data/bundles/impl/shim/hbase/HBaseServiceImpl.java
common-fragment-V1/src/main/java/com/pentaho/big/data/bundles/impl/shim/hive/HiveDriver.java
common-fragment-V1/src/test/java/com/pentaho/big/data/bundles/impl/shim/hbase/HBaseServiceFactoryTest.java
common-fragment-V1/src/test/java/com/pentaho/big/data/bundles/impl/shim/hbase/HBaseServiceImplTest.java
common-fragment-V1/src/test/java/com/pentaho/big/data/bundles/impl/shim/hdfs/HadoopFileSystemFactoryImplTest.java
common-fragment-V1/src/test/java/com/pentaho/big/data/bundles/impl/shim/hive/HiveDriverTest.java

[BACKLOG-28399] Fix commented out unit tests, minor code issues

---

shims/hdp30/driver/src/main/java/org/pentaho/hadoop/shim/HadoopShim.java

[BACKLOG-30909] Need to set Configuration.setRestrictSystemProperties to

---

shims/cdh514/driver/pom.xml
shims/cdh61/driver/pom.xml

Remove duplicated dependency (hadoop-yarn-api)

---

shims/cdh514/driver/pom.xml
shims/cdh61/driver/pom.xml

Resubmitting the PR because it was "lost" with the revert's.
@angel-ramoscardona

[CLEANUP] Remove duplicated dependency (hadoop-yarn-api)

---

common-fragment-V1/src/main/java/com/pentaho/big/data/bundles/impl/shim/hive/HiveDriver.java
common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/ShimConfigsLoader.java

[BACKLOG-31103] Method change to avoid hadoop library version

---

common-dependencies-V1/pom.xml
common-fragment-V1/pom.xml
mapreduce/pom.xml

This is part of a series of PRs. See https://github.com/pentaho/maven-parent-poms/pull/170 for details.
**Don't merge before the PR above.**

[PPP-4448] Use of Vulnerable Component - XStream 1.4.10

---

common-fragment-V1/src/main/java/org/pentaho/big/data/impl/shim/HadoopClientServicesImpl.java
common-fragment-V1/src/main/java/org/pentaho/big/data/impl/shim/mapreduce/JarUtility.java
common-fragment-V1/src/main/java/org/pentaho/big/data/impl/shim/mapreduce/MapReduceJobBuilderImpl.java
common-fragment-V1/src/main/java/org/pentaho/big/data/impl/shim/mapreduce/MapReduceServiceImpl.java
common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/format/avro/AvroInputField.java
common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/format/avro/AvroNestedFieldGetter.java
common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/format/orc/PentahoOrcInputFormat.java
common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/format/orc/PentahoOrcOutputFormat.java
common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/format/orc/PentahoOrcRecordReader.java
common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/format/parquet/delegate/DelegateFormatFactory.java
common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/format/parquet/delegate/apache/PentahoApacheInputFormat.java
common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/format/parquet/delegate/apache/PentahoApacheOutputFormat.java
common-fragment-V1/src/test/java/com/pentaho/big/data/bundles/impl/shim/hive/HiveDriverTest.java
common-fragment-V1/src/test/java/org/pentaho/big/data/impl/shim/pig/WriterAppenderManagerTest.java
common-fragment-V1/src/test/java/org/pentaho/hadoop/shim/common/DistributedCacheUtilImplOSDependentTest.java
common-fragment-V1/src/test/java/org/pentaho/hadoop/shim/common/format/parquet/PentahoParquetOutputFormatTest.java
common-services-api/src/main/java/org/pentaho/big/data/api/cluster/service/locator/impl/NamedClusterServiceLocatorImpl.java

logging, removing unused fields, etc.

[CLEANUP]  Sonar lint.  Consolidating some dups, try-with-resources,

---

common-services-api/src/main/java/org/pentaho/big/data/api/cluster/service/locator/impl/NamedClusterServiceLocatorImpl.java
common-services-api/src/test/java/org/pentaho/big/data/api/cluster/service/locator/impl/NamedClusterServiceLocatorImplTest.java
common-services-api/src/test/java/org/pentaho/bigdata/api/hdfs/impl/HadoopFileSystemLocatorImplTest.java

[TEST]  Moving common-services-api tests to correct directory

---

common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/ShimConfigsLoader.java
common-fragment-V1/src/main/resources/org/pentaho/hadoop/shim/messages/messages_en_US.properties
common-fragment-V1/src/test/java/org/pentaho/hadoop/shim/common/format/orc/PentahoOrcInputFormatTest.java
common-fragment-V1/src/test/java/org/pentaho/hadoop/shim/common/format/orc/PentahoOrcReadWriteTest.java
common-fragment-V1/src/test/java/org/pentaho/hadoop/shim/common/format/parquet/PentahoParquetInputFormatTest.java
common-fragment-V1/src/test/java/org/pentaho/hadoop/shim/common/format/parquet/PentahoParquetOutputFormatTest.java

carte jobs running on a cluster.

[BACKLOG-30160] Copy metastore to big-data-plugin directory for use in

---

common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/ShimConfigsLoader.java
common-fragment-V1/src/main/resources/org/pentaho/hadoop/shim/messages/messages_en_US.properties

Reverts pentaho/pentaho-hadoop-shims#1048

Revert "[BACKLOG-30822] Add error logging when site config files not found."

---

common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/ShimConfigsLoader.java

[BACKLOG-32189] Ensure file path resolution works on Windows as well as

---

common-fragment-V1/pom.xml
common-fragment-V1/src/main/java/org/pentaho/big/data/impl/shim/format/FormatServiceImpl.java
common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/CommonFormatShim.java
common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/format/parquet/delegate/DelegateFormatFactory.java
common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/format/parquet/delegate/apache/PentahoApacheInputFormat.java
common-fragment-V1/src/main/resources/org/pentaho/hadoop/shim/messages/messages_en_US.properties
shims/apache/README.md
shims/apache/driver/pom.xml
shims/apache/driver/src/main/java/org/pentaho/hadoop/shim/pvfs/PvfsHadoopBridge.java
shims/apache/driver/src/main/java/org/pentaho/hadoop/shim/pvfs/SelfSignedS3ClientFactory.java
shims/apache/driver/src/main/java/org/pentaho/hadoop/shim/pvfs/conf/HCPConf.java
shims/apache/driver/src/main/java/org/pentaho/hadoop/shim/pvfs/conf/PvfsConf.java
shims/apache/driver/src/main/java/org/pentaho/hadoop/shim/pvfs/conf/S3Conf.java
shims/apache/driver/src/main/resources/META-INF/services/org.apache.hadoop.fs.FileSystem
shims/apache/driver/src/test/java/org/pentaho/hadoop/shim/pvfs/PvfsHadoopBridgeTest.java
shims/apache/driver/src/test/java/org/pentaho/hadoop/shim/pvfs/SelfSignedS3ClientFactoryTest.java
shims/apache/driver/src/test/java/org/pentaho/hadoop/shim/pvfs/conf/HCPConfTest.java
shims/apache/driver/src/test/java/org/pentaho/hadoop/shim/pvfs/conf/S3ConfTest.java

Adds a pvfs bridging fs.  See README.md for details
https://jira.pentaho.com/browse/BACKLOG-30638
https://jira.pentaho.com/browse/BACKLOG-30731

[BACKLOG-30638][BACKLOG-30731] Parquet In/Out support with S3/HCP

---

common-fragment-V1/src/main/java/com/pentaho/big/data/bundles/impl/shim/hive/HiveDriver.java
common-fragment-V1/src/main/java/com/pentaho/big/data/bundles/impl/shim/hive/ImpalaDriver.java
common-fragment-V1/src/main/java/com/pentaho/big/data/bundles/impl/shim/hive/ImpalaSimbaDriver.java
shims/cdh61/driver/src/main/resources/OSGI-INF/blueprint/blueprint.xml

containing "impala". Use Cloudera driver for impala.

[BACKLOG-31132] Ensure Impala classes can get called for jdbc strings

---

common-fragment-V1/src/main/java/com/pentaho/big/data/bundles/impl/shim/hive/HiveDriver.java

[BACKLOG-31132] Suppress error and stack trace if Cloudera jars are

---

common-fragment-V1/src/main/java/org/pentaho/big/data/impl/shim/format/FormatServiceImpl.java
common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/CommonFormatShim.java
common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/format/HadoopFormatBase.java
common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/format/orc/PentahoOrcOutputFormat.java
common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/format/parquet/delegate/DelegateFormatFactory.java
common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/format/parquet/delegate/apache/PentahoApacheInputFormat.java
common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/format/parquet/delegate/apache/PentahoApacheOutputFormat.java
common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/format/parquet/delegate/twitter/PentahoTwitterInputFormat.java
common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/format/parquet/delegate/twitter/PentahoTwitterOutputFormat.java
common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/spi/FormatShim.java
common-services-api/src/main/java/org/pentaho/big/data/api/cluster/service/locator/impl/NamedClusterServiceLocatorImpl.java
shim-api/src/main/java/org/pentaho/hadoop/shim/api/cluster/NamedClusterServiceLocator.java
shim-api/src/main/java/org/pentaho/hadoop/shim/api/format/AvroSpec.java
shim-api/src/main/java/org/pentaho/hadoop/shim/api/format/FormatService.java
shim-api/src/main/java/org/pentaho/hadoop/shim/api/format/OrcSpec.java
shim-api/src/main/java/org/pentaho/hadoop/shim/api/format/ParquetSpec.java

[CLEANUP]  Removing 'throws Exception'

---

common-fragment-V1/src/main/java/org/pentaho/big/data/impl/shim/mapreduce/MapReduceServiceImpl.java

[BACKLOG-32247] Add site config files to classpath when running Hadoop

---

common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/format/avro/AvroNestedRecordReader.java

[BACKLOG-32173] Ensure file stream gets closed when this object is

---

common-services-api/src/main/java/org/pentaho/big/data/api/jdbc/impl/JdbcUrlImpl.java

[BACKLOG-32809] Need to parse the URL manually to handle possible spaces

---

shims/apache/driver/pom.xml

https://jira.pentaho.com/browse/BACKLOG-32909

[BACKLOG-32909] Apache Shim - Update ORC Jar

---

common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/CommonHadoopShim.java
common-services-api/src/main/java/org/pentaho/big/data/api/shims/LegacyShimLocator.java

[BACKLOG-32812] Create a property to control the number of timeouts when

---

common-fragment-V1/src/main/java/org/pentaho/hbase/shim/fake/FakeNamedCluster.java
shim-api/src/main/java/org/pentaho/hadoop/shim/api/cluster/NamedCluster.java

* [BAD-1907] Updating License Headers

[BAD-1907] Plain text password is stored in the shim configuration files

---

common-fragment-V1/src/main/java/org/pentaho/hbase/shim/fake/FakeNamedCluster.java
shim-api/src/main/java/org/pentaho/hadoop/shim/api/cluster/NamedCluster.java

This reverts commit c7089b7127dc8d6992c6687e3085589d2c279258, reversing
changes made to cb914506944886b046ac41ec944ce8c6ab0409f7.
* Left License Update in
PR is a set of Revert PRs:
- https://github.com/pentaho/pentaho-hadoop-shims/pull/1125
- https://github.com/pentaho/pentaho-yarn-kettle-plugin/pull/404
- https://github.com/pentaho/big-data-plugin/pull/2041
- https://github.com/pentaho/pentaho-big-data-ee/pull/445
- https://github.com/pentaho/pentaho-kettle/pull/7336

Revert "Merge pull request #1116 from gryphendowre/SP-5422"

---

common-dependencies-V1/pom.xml
common-fragment-V1/pom.xml
common-services-api/pom.xml
pom.xml
shims/apache/driver/pom.xml
shims/cdh514/driver/pom.xml
shims/cdh61/driver/pom.xml
shims/dataproc1421/driver/pom.xml
shims/dataproc1421/pom.xml
shims/emr521/driver/pom.xml
shims/hdp26/driver/pom.xml
shims/hdp30/driver/pom.xml
shims/mapr60/driver/pom.xml
shims/pom.xml

@lucboudreau 
tested resolution off-VPN with plugin cleaned from cache

[ENGOPS-6788] GAV changes for open-sourced shim-bundle-plugin

---

common-fragment-V1/src/main/java/org/pentaho/big/data/impl/shim/mapreduce/PentahoMapReduceJobBuilderImpl.java
common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/api/internal/DistributedCacheUtil.java
common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/DistributedCacheUtilImpl.java
common-fragment-V1/src/test/java/org/pentaho/hadoop/shim/common/DistributedCacheTestUtil.java
common-fragment-V1/src/test/java/org/pentaho/hadoop/shim/common/DistributedCacheUtilImplOSDependentTest.java
common-fragment-V1/src/test/java/org/pentaho/hadoop/shim/common/DistributedCacheUtilImplTest.java

are pulled into a PMR deployment to the cluster.

[PDI-18840] Provide a way to exclude individual files from plugins that

---

common-fragment-V1/src/main/java/org/pentaho/hadoop/shim/common/format/orc/OrcConverter.java

contains the same repeating value throughout the file.

[BACKLOG-33417] Correctly handle files where one or more columns

---

api/src/main/java/org/pentaho/hadoop/shim/api/DistributedCacheUtil.java
common/common-shim/src/main/java/org/pentaho/hadoop/shim/common/DistributedCacheUtilImpl.java
common/common-shim/src/test/java/org/pentaho/hadoop/shim/common/DistributedCacheTestUtil.java
common/common-shim/src/test/java/org/pentaho/hadoop/shim/common/DistributedCacheUtilImplOSDependentTest.java
common/common-shim/src/test/java/org/pentaho/hadoop/shim/common/DistributedCacheUtilImplTest.java

files from plugins that are pulled into a PMR deployment to the cluster.

[SP-5678] Backport of PDI-18840.  Provide a way to exclude individual

---

common-fragment-V1/src/main/java/org/pentaho/big/data/impl/shim/mapreduce/MapReduceServiceImpl.java

object and not the file system.

[BACKLOG-34471] Updated to get cluster config files from named cluster

---

common-fragment-V1/src/main/java/org/pentaho/big/data/impl/shim/mapreduce/MapReduceServiceImpl.java

[BACKLOG-34472] Fixed GUI issue with driver class drop-down not

---

api/src/main/java/org/pentaho/hbase/shim/spi/HBaseConnection.java
common/common-hbase-comparators-api/src/main/java/org/pentaho/hbase/shim/common/wrapper/HBaseConnectionInterface.java
common/common-shim/src/main/java/org/pentaho/hbase/shim/common/CommonHBaseConnection.java
common/common-shim/src/main/java/org/pentaho/hbase/shim/fake/FakeHBaseConnection.java
common/hbase-comparators/src/main/java/org/pentaho/hbase/shim/common/HBaseConnectionImpl.java
common/hbase/src/main/java/org/pentaho/hadoop/hbase/factory/HBase10Admin.java
common/mapred/src/main/java/org/pentaho/hbase/factory/HBaseAdmin.java
common/modern/src/main/java/org/pentaho/hadoop/shim/common/delegating/DelegatingHBaseConnection.java

Reverts pentaho/pentaho-hadoop-shims#1174

Revert "[SP-5778] Enable namespace nomenclature on hbase input/output steps"

---

api/src/main/java/org/pentaho/hbase/shim/spi/HBaseConnection.java
common/common-hbase-comparators-api/src/main/java/org/pentaho/hbase/shim/common/wrapper/HBaseConnectionInterface.java
common/common-shim/src/main/java/org/pentaho/hbase/shim/common/CommonHBaseConnection.java
common/common-shim/src/main/java/org/pentaho/hbase/shim/fake/FakeHBaseConnection.java
common/hbase-comparators/src/main/java/org/pentaho/hbase/shim/common/HBaseConnectionImpl.java
common/hbase/src/main/java/org/pentaho/hadoop/hbase/factory/HBase10Admin.java
common/mapred/src/main/java/org/pentaho/hbase/factory/HBaseAdmin.java
common/modern/src/main/java/org/pentaho/hadoop/shim/common/delegating/DelegatingHBaseConnection.java

Reverts pentaho/pentaho-hadoop-shims#1176

Revert "Revert "[SP-5778] Enable namespace nomenclature on hbase input/output steps""

---

api/src/main/java/org/pentaho/hbase/shim/spi/HBaseConnection.java
common/common-hbase-comparators-api/src/main/java/org/pentaho/hbase/shim/common/wrapper/HBaseConnectionInterface.java
common/common-shim/src/main/java/org/pentaho/hbase/shim/common/CommonHBaseConnection.java
common/common-shim/src/main/java/org/pentaho/hbase/shim/fake/FakeHBaseConnection.java
common/hbase-comparators/src/main/java/org/pentaho/hbase/shim/common/HBaseConnectionImpl.java
common/hbase/src/main/java/org/pentaho/hadoop/hbase/factory/HBase10Admin.java
common/mapred/src/main/java/org/pentaho/hbase/factory/HBaseAdmin.java
common/modern/src/main/java/org/pentaho/hadoop/shim/common/delegating/DelegatingHBaseConnection.java

Reverts pentaho/pentaho-hadoop-shims#1177

Revert "Revert "[SP-5778] Enable namespace nomenclature on hbase input/output…"

---

shims/apache/driver/pom.xml
shims/apache/driver/src/main/java/org/pentaho/hadoop/shim/pvfs/PvfsHadoopBridge.java
shims/apache/driver/src/main/java/org/pentaho/hadoop/shim/pvfs/conf/ADLSGen2Conf.java
shims/apache/driver/src/main/java/org/pentaho/hadoop/shim/pvfs/conf/providers/PentahoAzureSasTokenProvider.java
shims/apache/driver/src/main/resources/META-INF/services/org.apache.hadoop.fs.FileSystem
shims/apache/driver/src/test/java/org/pentaho/hadoop/shim/pvfs/conf/ADLSGen2ConfTest.java

Master Branch PR's:
- https://github.com/pentaho/pentaho-hadoop-shims/pull/1188

[BACKLOG-34482] Backport of ORC/Parquet support for ADLS2 VFS

---

shims/cdpdc71/driver/pom.xml

Master Branch PR: 
https://github.com/pentaho/pentaho-hadoop-shims/pull/1197

Backport of [BACKLOG-34725] Update CDP DC Shim version to 7.1.4 dependencies

---

common-fragment-V1/src/main/java/org/pentaho/big/data/impl/shim/HadoopClientServicesImpl.java

Removed conditional check for MapR Where it had empty implementation

[BACKLOG-34990] -Sqoop fix for MapR

---

shim-api/pom.xml
shim-api/src/main/java/org/pentaho/hadoop/shim/api/cluster/NamedCluster.java

[CUST-253] - Requesting CUST for BAD-1920

---

common-dependencies-V1/pom.xml
common-fragment-V1/pom.xml
common-fragment-V1/src/main/java/org/pentaho/big/data/impl/shim/mapreduce/PentahoMapReduceJobBuilderImpl.java
mapreduce/pom.xml

[CUST-261] - Requesting CUST for BAD-1918 on 9.2.0.3

---

common-fragment-V1/src/test/java/org/pentaho/big/data/impl/shim/mapreduce/PentahoMapReduceJobBuilderImplTest.java

@smmribeiro 
@bcostahitachivantara 
@renato-s

BACKLOG-35760 - Address failing tests in big-data-hadoop-shims-common

---

api/pom.xml
common/mapred/pom.xml

@renato-s 
@smmribeiro 
@bcostahitachivantara

[SP-6106] - Correct unit test failures related to log4j changes

---

shims/apache/driver/pom.xml
shims/cdh61/driver/pom.xml
shims/cdpdc71/driver/pom.xml
shims/hdi40/driver/pom.xml
shims/hdp30/driver/pom.xml

[PPP-4870]-Jetty Security Vulnerability -CVE-2022-2048
[PPP-4870]: https://hv-eng.atlassian.net/browse/PPP-4870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PPP-4870]-Jetty Security Vulnerability -CVE-2022-2048

---

shims/apache/driver/pom.xml
shims/cdh61/driver/pom.xml
shims/cdpdc71/driver/pom.xml
shims/hdi40/driver/pom.xml
shims/hdp30/driver/pom.xml

[Revert] "[PPP-4870]-Jetty Security Vulnerability -CVE-2022-2048"
[PPP-4870]: https://hv-eng.atlassian.net/browse/PPP-4870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Revert] "[PPP-4870]-Jetty Security Vulnerability -CVE-2022-2048"

---

mapreduce/pom.xml

[TEST] Adding log4j dependencies; not getting pulled in although needed

---

pom.xml
shims/cdpdc71/driver/pom.xml
shims/dataproc1421/driver/pom.xml
shims/emr521/driver/pom.xml
shims/hdi40/driver/pom.xml
shims/hdp30/driver/pom.xml
shims/mapr60/driver/pom.xml
shims/mapr61/driver/pom.xml

@smmribeiro 
@renato-s 
Fixing problem with transient dependencies

[PPP-4865] - Vulnerable component Snakeyaml - Fixing problem with transient dependencies

---

shims/pom.xml

BACKLOG-41141 - Added ApacheVanilla module in pom

BACKLOG-41141 - Added ApacheVanilla module in pom

---

common-fragment-V1/pom.xml
shims/apache/driver/pom.xml

[PPP-5083]-Vulnerable Component: ion java
[PPP-5083]: https://hv-eng.atlassian.net/browse/PPP-5083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PPP-5083]-Vulnerable Component: ion java

---

shims/apache/driver/pom.xml
shims/apachevanilla/driver/pom.xml
shims/cdh61/driver/pom.xml
shims/cdpdc71/driver/pom.xml
shims/dataproc1421/driver/pom.xml
shims/emr521/driver/pom.xml
shims/emr700/driver/pom.xml
shims/hdi40/driver/pom.xml
shims/hdp30/driver/pom.xml

…s that has velocity as transitive dependency

[PPP-4892] removing the velocity library dependency from all the shims that has velocity as transitive dependency

---

shims/apache/driver/pom.xml

[ PPP-4976 ] - Vulnerable Component: hadoop-common, hadoop-hdfs, hadoop-yarn-server [Apache Shim]

---

common-fragment-V1/src/main/java/org/pentaho/big/data/impl/shim/HadoopClientServicesImpl.java

This reverts commit 2aa2a7b2643cd4ff3aec8e77cab280e0192bb69c.

Revert "[PPP-4743] - Added changes for Vulnerable Component: Jackson ASL (hadoop-shims plugin)"

---

shims/apache/driver/pom.xml

[PPP-4976] - Vulnerable Component: hadoop-common, hadoop-hdfs, hadoop-yarn-server [Apache Shim]

---

shims/apache/driver/pom.xml
shims/apachevanilla/driver/pom.xml
shims/cdh61/driver/pom.xml
shims/cdpdc71/driver/pom.xml
shims/dataproc1421/driver/pom.xml
shims/dataproc1421/pom.xml
shims/emr700/driver/pom.xml
shims/hdi40/driver/pom.xml

There will still be an old jetty transitive in the emr700 shim -- looking into what to do there

[PPP-5035] Update jetty in shims

---

shims/apachevanilla/driver/pom.xml
shims/cdpdc71/driver/pom.xml

Reverts pentaho/pentaho-hadoop-shims#1465

Revert "[BACKLOG-42288] Excluded logback-classic from CDP and Apache drivers"

---

shims/apache/driver/pom.xml

[SP-6603]-Backport of PPP-4976 - Vulnerable Component: hadoop-common, hadoop-hdfs, hadoop-yarn-server [Apache Shim] 3.3.0 (10.2 Suite)
[SP-6603]: https://hv-eng.atlassian.net/browse/SP-6603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SP-6603]-Backport of PPP-4976 - Vulnerable Component: hadoop-common, hadoop-hdfs, hadoop-yarn-server [Apache Shim] 3.3.0 (10.2 Suite)

---

shims/apache/driver/pom.xml
shims/apachevanilla/driver/pom.xml
shims/cdh61/driver/pom.xml
shims/cdpdc71/driver/pom.xml
shims/dataproc1421/driver/pom.xml
shims/emr700/driver/pom.xml
shims/hdi40/driver/pom.xml

Covers:
- https://github.com/pentaho/pentaho-hadoop-shims/pull/1447
- https://github.com/pentaho/pentaho-hadoop-shims/pull/1453
- https://github.com/pentaho/pentaho-hadoop-shims/pull/1454
- https://github.com/pentaho/pentaho-hadoop-shims/pull/1473
- https://github.com/pentaho/pentaho-hadoop-shims/pull/1474

[SP-6606] Backport Jetty upgrades

---

shims/apache/driver/pom.xml
shims/apachevanilla/driver/pom.xml
shims/cdpdc71/driver/pom.xml
shims/dataproc1421/driver/pom.xml
shims/dataproc1421/pom.xml

BACKPORT of PRs for https://hv-eng.atlassian.net/browse/PPP-4582
Includes: 
972346f8f664ab426deaf00959a84eb904fff94c
3f9d6a23ed95f0f6bfde1871169da64c32d8990e
24ec3d2c42e4d66253ea0c44791f63753dbb547d
55943c97976e61237ab33e92c667fcc80f9eaf5b
210ba0ecc661e77e443d7ecb975ac37f27a9bc23
47c6a76c36b0b0d7fa4ccdf2ca54b628402fb8d9

[SP-6608] Backport of PPP-4582 - Use of Vulnerable Component: Components/oauth_client_library_for_java (10.2 Suite)

---

pom.xml
shims/apache/driver/pom.xml
shims/apachevanilla/driver/pom.xml
shims/cdh61/driver/pom.xml
shims/cdpdc71/driver/pom.xml
shims/dataproc1421/driver/pom.xml
shims/emr700/driver/pom.xml
shims/hdi40/driver/pom.xml

[BACKLOG-42757]-Upgrading pentaho-hadoop-shims from Java EE to Jakarta EE
[BACKLOG-42757]: https://hv-eng.atlassian.net/browse/BACKLOG-42757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-42757]-Upgrading pentaho-hadoop-shims from Java EE to Jakarta EE

---

pom.xml

Merge pull request #1480 from smaring/DEVO-10693-10.2.0.0
[DEVO-10639] remove oss license html attachments
(cherry picked from commit 59a8b0fbf5ac2de7e00bf4521e08eabb8f2b4a1a)
[DEVO-10639]: https://hv-eng.atlassian.net/browse/DEVO-10639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PPP-5411] License Notice in EE Splash Screen Cherry Picks: Remove oss license html attachments

---

common-fragment-V1/pom.xml
shims/apache/driver/pom.xml

[SP-6643]-Backport of PPP-5083 - Vulnerable Component: ion java (10.2 Suite)
[SP-6643]: https://hv-eng.atlassian.net/browse/SP-6643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SP-6643]-Backport of PPP-5083 - Vulnerable Component: ion java (10.2 Suite)

---

shims/apache/driver/pom.xml
shims/cdpdc71/driver/pom.xml
shims/dataproc1421/pom.xml
shims/hdp30/driver/pom.xml

[SP-6634] Backporting PPP-4780 upgrading libthrift library to avoid security issues

---

shims/apachevanilla/driver/pom.xml
shims/dataproc1421/driver/pom.xml
shims/emr700/driver/pom.xml

For: apachevanilla, dataproc1421 and emr700
For PPP-5605
@pentaho/tatooine_dev

build: upgrade curator-client to 5.6.0

---

shims/apache/driver/pom.xml
shims/apachevanilla/driver/pom.xml
shims/dataproc1421/driver/pom.xml
shims/emr700/driver/pom.xml

Original PRs:
- https://github.com/pentaho/pentaho-hadoop-shims/pull/1559
- https://github.com/pentaho/pentaho-hadoop-shims/pull/1561
@pentaho/tatooine_dev

[SP-6789] Backport of PPP-5605 - Vulnerable Component: guava within curator-client-5.2.0.jar (10.2 Suite)

---

shims/apache/driver/pom.xml
shims/apachevanilla/driver/pom.xml
shims/cdpdc71/driver/pom.xml
shims/dataproc1421/driver/pom.xml
shims/emr700/driver/pom.xml

[PPP-5585] Vulnerable Component: Jetty (deep scan)

---

shims/apache/driver/pom.xml

Use the default jetty version for org.eclipse.jetty.websocket groupId
@pentaho/tatooine_dev

feat[PPP-5585]: upgrade org.eclipse.jetty.websocket artifacts

---

common-fragment-V1/pom.xml

[BACKLOG-43098]-Fixing broken testcases as part of tomcat upgradation
[BACKLOG-43098]: https://hv-eng.atlassian.net/browse/BACKLOG-43098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-43098]-Fixing broken testcases as part of tomcat upgradation

---

shims/apache/driver/pom.xml
shims/apachevanilla/driver/pom.xml
shims/cdpdc71/driver/pom.xml
shims/dataproc1421/driver/pom.xml
shims/emr700/driver/pom.xml

[SP-6841] Backport of PPP-5585

---

common-dependencies-V1/pom.xml
common-fragment-V1/pom.xml
shims/apache/driver/pom.xml
shims/apachevanilla/driver/pom.xml
shims/apachevanilla/pmr/pom.xml
shims/cdh514/driver/pom.xml
shims/cdh61/driver/pom.xml
shims/cdh61/pmr/pom.xml
shims/cdpdc71/driver/pom.xml
shims/cdpdc71/pmr/pom.xml
shims/dataproc1421/driver/pom.xml
shims/dataproc1421/pmr/pom.xml
shims/emr521/driver/pom.xml
shims/emr700/driver/pom.xml
shims/hdi40/driver/pom.xml
shims/hdi40/pmr/pom.xml
shims/hdp26/driver/pom.xml
shims/hdp30/driver/pom.xml
shims/mapr60/driver/pom.xml
shims/mapr61/driver/pom.xml

Original PR's: 
1. https://github.com/pentaho/pentaho-hadoop-shims/pull/1569
2. https://github.com/pentaho/pentaho-hadoop-shims/pull/1577
This also includes changes from https://hv-eng.atlassian.net/browse/PPP-5689

[SP-6842] Backport of PPP-5579 - Vulnerable Component: com.nimbusds:nimbus-jose-jwt:9.31 (10.2 Suite)

---

shims/apachevanilla/driver/pom.xml
shims/emr700/driver/pom.xml

[SP-6844] backporting PPP-5699, upgrading apachevanilla to 0.16.0 and emr700 to 0.13.0

---

common-fragment-V1/src/main/java/org/pentaho/big/data/impl/shim/mapreduce/PentahoMapReduceJobBuilderImpl.java
shims/cdpdc71/driver/pom.xml
shims/dataproc1421/driver/pom.xml
shims/hdi40/driver/pom.xml

Changes references: https://protobuf.dev/news/2025-01-23/ and https://hv-eng.atlassian.net/browse/PPP-5759

[PPP-5762] Allow PMR jobs on CDP to run without issue

---

shims/emr770/driver/pom.xml

[BACKLOG-44539]-EMR : PMR job is not running when timeline service is enabled
[BACKLOG-44539]: https://hv-eng.atlassian.net/browse/BACKLOG-44539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-44539]-EMR : PMR job is not running when timeline service is enabled
